### DISCUSSION TITLE
To clarify: can I use Infisical for secret management in the same cluster in which it is hosted?

### DISCUSSION THREAD

**Discussion by loganmarchione** [Infisical/infisical#2826] [General]
I'm looking at self-hosting Infisical in a K3s cluster. But there is a chicken/egg problem where I need Infisical running to unlock secrets, but Infisical itself needs a secret. Can I use Infisical for secret management in the same cluster in which it is hosted?

I found [this](https://infisical.com/docs/self-hosting/deployment-options/kubernetes-helm) page which seems to suggest this will work by creating a secret on the cluster manually. 

```
apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
type: Opaque
stringData:
  AUTH_SECRET: <>
  ENCRYPTION_KEY: <>
  SITE_URL: <>
```

What happens to the other apps secrets until Infisical is unlocked/running?
