### ISSUE TITLE
[ENG-136] Issues with google sso

### ISSUE THREAD

**Issue by markksuite** [Infisical/infisical#1035]
Using latest version of infisical frontend and backend (v.0.36.2) + mongo + redis, self hosted.

When pressing "Continue with Google" button (during login procs.), infisical redirects me to: `https://subdomain.mydomain.com/api/v1/sso/subdomain.mydomain.com/login/sso?token=sometokenhere`.

And shows blank json response:
![image](https://github.com/Infisical/infisical/assets/134363906/1a6fc2d4-a125-4748-8bdd-714bd257ad2a)

But, after I edit first part of url and delete `subdomain.mydomain.com/api/v1/sso/` at the beginning of generated url (new address: `https://subdomain.mydomain.com/login/sso?token=sometokenhere)`:
![image](https://github.com/Infisical/infisical/assets/134363906/7fc9ab45-455a-47fa-8441-d35111778c03)

Infisical succesfully accepts my auth request.

Looks like in self-hosted solution, app copies $SITE_URL environmental variable and paste it twice.

<sub>[ENG-136](https://linear.app/infisical/issue/ENG-136/issue-on-with-google-sso)</sub>

**Comment by markksuite** [comment]
Edited description (added more info) and issue title

**Comment by dangtony98** [comment]
Hey @markksuite,

I assume you've followed each step in the docs for Google SSO [here](https://infisical.com/docs/documentation/platform/sso/google)?

I would look into the redirect URL set in GCP as well as the `SITE_URL` environment variable being set in your instance of Infisical.

**Comment by markksuite** [comment]
@dangtony98 yes, and it works, if i remove the repeated url address

**Comment by markksuite** [comment]
![env](https://github.com/Infisical/infisical/assets/134363906/86f54fb0-f12b-462d-9e8f-ec40febc5f88)
Here is my env vars (running in kube, v.0.36.2 docker image)

**Comment by markksuite** [comment]
Google api:
![env2](https://github.com/Infisical/infisical/assets/134363906/3ea78469-433c-4b23-a745-a214690f2200)

**Comment by dangtony98** [comment]
Awesome so we can consider this issue resolved? @markksuite

**Comment by markksuite** [comment]
I still have the same issue, url is repeated twice (so it works only if you mannually edit url link, in browser, every time)

**Comment by markksuite** [comment]
Sorry, forgetting about tags.
@dangtony98

**Comment by m7salam** [comment]
I have this same exact issue now 

all configured right and her eis a video walkthrough https://www.loom.com/share/1fab2fba7b0c4810856ffa1ff1cbe728

so is this ever fixed ?

**Comment by markksuite** [comment]
Using self-host, infisical-standalone helm chart, infisical:v0.149.0, works without issues.

This was fixed in ~a month (or so) after creation of this post (replaced the docker image with latest release at that time), since then (do all apps upgrades at least once a month), have no issues with direct of google sso.

**Comment by m7salam** [comment]
> Using self-host, infisical-standalone helm chart, infisical:v0.149.0, works without issues.
> 
> This was fixed in ~a month (or so) after creation of this post (replaced the docker image with latest release at that time), since then (do all apps upgrades at least once a month), have no issues with direct of google sso.

everything was working fine with me up until 3 days ago, something definitely happened im using the `infisical/infisical:latest-postgres
`  docker image, and the version im getting from the terminal is `infisical version 0.41.89` which also feels weird and old

**Comment by markksuite** [comment]
Yea, latest-postgres is not supported (tag) anymore, try to use version tag like `v0.149.0` or `latest`.

They removed ending `postgres`, that showed that it's not mongo db version (as, I think, mongo db release is now completely deprecated, only postgres releases maintained)

**Comment by markksuite** [comment]
If you want to keep all data - backup db, then do upgrade - image tags, but do it with 5-10 major versions a time, `0.41.*` -> `0.46.*` -> `0.51.*`, as those would run migration steps every time, usually upgraded with 5-10 major versions, not sure if simple `latest-postgres` -> `latest` will work. 

Also `latest` is literally latest (stable + nightly) release (now it is `v0.150.0-nightly-20251007`, I would recommend to use version tagging)

**Comment by markksuite** [comment]
IMPORTANT:
Looks like `0.41.89` is your infisical cli version, as there was not such server release.
But CLI exists: https://hub.docker.com/r/infisical/cli/tags?name=0.41.89

**Comment by markksuite** [comment]
UPD, I remembered where I saw this versions tag (at least very close value):

<img width="876" height="401" alt="Image" src="https://github.com/user-attachments/assets/398615a2-1618-48fe-9e94-cb7566261c1a" />

That is default infisical-cli value in infisical-standalone helm chart: https://artifacthub.io/packages/helm/infisical/infisical-standalone?modal=values

**Comment by m7salam** [comment]
> Yea, latest-postgres is not supported (tag) anymore, try to use version tag like `v0.149.0` or `latest`.
> 
> They removed ending `postgres`, that showed that it's not mongo db version (as, I think, mongo db release is now completely deprecated, only postgres releases maintained)

if i simply changed the tag to latest, would it still work with my docker-compose structure or i would need to do a lot of changes 

this is my compose structure

```
services:
  backend:
    image: 'infisical/infisical:latest-postgres'
    environment:
      - SERVICE_FQDN_BACKEND_8080
      - 'SITE_URL=${SERVICE_FQDN_BACKEND_8080}'
      - 'NODE_ENV=${NODE_ENV:-production}'
      - 'ENCRYPTION_KEY=${SERVICE_PASSWORD_ENCRYPTIONKEY}'
      - 'AUTH_SECRET=${SERVICE_REALBASE64_64_AUTHSECRET}'
      - 'SMTP_HOST=${SMTP_HOST}'
      - 'SMTP_USERNAME=${SMTP_USERNAME}'
      - 'SMTP_PASSWORD=${SMTP_PASSWORD}'
      - 'SMTP_PORT=${SMTP_PORT}'
      - 'SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}'
      - 'SMTP_FROM_NAME=${SMTP_FROM_NAME}'
      - 'INF_APP_CONNECTION_GITHUB_APP_CLIENT_ID=${INF_APP_CONNECTION_GITHUB_APP_CLIENT_ID}'
      - 'INF_APP_CONNECTION_GITHUB_APP_CLIENT_SECRET=${INF_APP_CONNECTION_GITHUB_APP_CLIENT_SECRET}'
      - 'INF_APP_CONNECTION_GITHUB_APP_SLUG=${INF_APP_CONNECTION_GITHUB_APP_SLUG}'
      - 'INF_APP_CONNECTION_GITHUB_APP_ID=${INF_APP_CONNECTION_GITHUB_APP_ID}'
      - 'INF_APP_CONNECTION_GITHUB_APP_PRIVATE_KEY=${INF_APP_CONNECTION_GITHUB_APP_PRIVATE_KEY}'
      - 'DB_CONNECTION_URI=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@db:5432/${POSTGRES_DB}'
      - 'REDIS_URL=redis://redis:6379'
      - 'CLIENT_ID_GOOGLE_LOGIN=${CLIENT_ID_GOOGLE_LOGIN}'
      - 'CLIENT_SECRET_GOOGLE_LOGIN=${CLIENT_SECRET_GOOGLE_LOGIN}'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1500m
        reservations:
          cpus: '0.5'
          memory: 512m
    healthcheck:
      test:
        - CMD-SHELL
        - 'wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/api/status || exit 1'
    logging:
      driver: fluentd
      options:
        fluentd-address: 'localhost:24224'
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  redis:
    image: 'redis:7'
    volumes:
      - 'redis-data:/data'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512m
    healthcheck:
      test:
        - CMD-SHELL
        - 'redis-cli -h localhost -p 6379 ping'
      interval: 5s
      timeout: 5s
      retries: 3
    logging:
      driver: fluentd
      options:
        fluentd-address: 'localhost:24224'
  db:
    image: 'postgres:14-alpine'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DB:-infisical}'
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 1536m
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 10s
      retries: 10
    logging:
      driver: fluentd
      options:
        fluentd-address: 'localhost:24224'


```
