### ISSUE TITLE
[ENG-142] Add labels/annotations support on generated Kubernetes Secrets

### ISSUE THREAD

**Issue by asoc** [Infisical/infisical#1042]
### Feature description

I would like the ability to specify labels and annotations that should be added to the generated `Secret` resource.

### Why would it be useful?

Some applications use labels/annotations for management or tracking purposes. For a specific example, ArgoCD supports declaring repository credentials via Secrets but requires a specific label on the Secret for it to be usable. [https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials)

Example from the link:

```
apiVersion: v1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/argoproj
  password: my-password
  username: my-username
```

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-142](https://linear.app/infisical/issue/ENG-142/add-labelsannotations-support-on-generated-kubernetes-secreds)</sub>
