### ISSUE TITLE
Support for creating a secret in multiple namespaces

### ISSUE THREAD

**Issue by MohammedNoureldin** [Infisical/infisical#1111]
### Feature description
Is it possible to support creating a secret in multiple namespaces?

For example to support passing a list of namespaces like this:

```
  managedSecretReference:
    secretName: managed-secret
    secretNamespace: ns1, ns2, ns3
```

### Why would it be useful?
By this, we will not need for third-party components to mirror the secret to other namespaces.

**Comment by imrefazekas** [comment]
Would be awesome indeed!

**Comment by varonix0** [comment]
HI @MohammedNoureldin and @imrefazekas, this has now been implemented!

You can create multiple managed secrets across different namespaces like so:


```yaml
  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: ns1
   - secretName: managed-secret
      secretNamespace: ns2
```

Please update to the latest version of the operator for these changes to take effect.

Please let me know if this helps!
