### ISSUE TITLE
[ENG-237] Infisical fails to authenticate with Redis in Docker Compose setup despite correct credentials

### ISSUE THREAD

**Issue by piotrszacilowski** [Infisical/infisical#1166]
### Describe the bug

The Infisical service within a docker-compose setup is unable to authenticate with a Redis instance, despite being provided with the correct REDIS_URL and password in the environment variables. This issue leads to a **NOAUTH Authentication** required error. Redis is secured with a password as it is used by other services, but Infisical seems unable to respect the authentication mechanism.

### To Reproduce

1. Set up a docker-compose.yml with Infisical and other services including Redis that is secured using password.

```
version: "3"

services:
  backend:
    image: infisical/infisical:latest
    restart: unless-stopped
    ports:
      - 80:8080
    env_file: .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  mongo:
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
  redis_data:
    driver: local
```

1. Create .env file:

```
ENCRYPTION_KEY=dummy
AUTH_SECRET=dummy

MONGO_URL=mongodb://root:example@mongo:27017/?authSource=admin
MONGO_USERNAME=root
MONGO_PASSWORD=mymongopassword

REDIS_URL=redis://:myredispassword@redis:6379
REDIS_PASSWORD=myredispassword
```

1. Run `docker-compose -f docker-compose.yml up -d` to start the services.
2. Observe that Infisical attempts to connect to Redis and fails with an authentication error.
   Check the logs of the Infisical service with `docker logs infisical-backend-1`.

```
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
Telemetry is enabled
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":50,"time":"2023-11-08T00:06:31.057Z","pid":1,"hostname":"9cc38c51def8","err":{"type":"Error","message":"connect ECONNREFUSED 127.0.0.1:587","stack":"Error: connect ECONNREFUSED 127.0.0.1:587\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)","errno":-111,"code":"ESOCKET","syscall":"connect","address":"127.0.0.1","port":587,"command":"CONN"},"msg":"SMTP - Failed to connect to undefined:587"}
/backend/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: NOAUTH Authentication required.
    at parseError (/backend/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/backend/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'client',
    args: [ 'setname', 'bull:Z2l0aHViLXB1c2gtZXZlbnQtc2VjcmV0LXNjYW5uaW5n' ]
  }
}
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
```

The error NOAUTH Authentication required is displayed, and the service is stuck in a restart loop.

### Expected behavior

When REDIS_URL with the correct password is provided in the environment variables, Infisical should be able to authenticate with the Redis instance successfully. The service should connect to Redis and function as expected without throwing authentication errors.

### Screenshots

N/A

### Platform you are having the issue on:

* Docker version 20.10.23
* Docker Compose version v2.15.1

### Additional context

The inability to authenticate with Redis is a significant concern as the Redis instance needs to be password-protected for security reasons. This behavior is unexpected and contradicts the functionality described in the documentation where Redis, if used, should be accessible by Infisical with proper credentials.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-237](https://linear.app/infisical/issue/ENG-237/infisical-fails-to-authenticate-with-redis-in-docker-compose-setup)</sub>

**Comment by maidul98** [comment]
Thank you for the bug report, we will try to reproduce this on our end and let you know the next steps we take to resolve this issue

**Comment by piotrszacilowski** [comment]
Great, thanks I'm waiting for the update.

Furthermore, by setting a MongoDB password other than: "example" and specifying it in MONGO_URL the Infiscal service also throws an error.

.env
```
MONGO_URL=mongodb://root:mymongopassword@mongo:27017/?authSource=admin
MONGO_USERNAME=root
MONGO_PASSWORD=mymongopassword
```

logs:
```
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
Telemetry is enabled
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":50,"time":"2023-11-08T13:43:02.275Z","pid":1,"hostname":"b88b63140001","err":{"type":"Error","message":"connect ECONNREFUSED 127.0.0.1:587","stack":"Error: connect ECONNREFUSED 127.0.0.1:587\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)","errno":-111,"code":"ESOCKET","syscall":"connect","address":"127.0.0.1","port":587,"command":"CONN"},"msg":"SMTP - Failed to connect to undefined:587"}
{"level":50,"time":"2023-11-08T13:43:02.288Z","pid":1,"hostname":"b88b63140001","err":{"type":"MongoServerError","message":"Authentication failed.","stack":"MongoServerError: Authentication failed.\n    at Connection.onMessage (/backend/node_modules/mongodb/lib/cmap/connection.js:202:26)\n    at MessageStream.<anonymous> (/backend/node_modules/mongodb/lib/cmap/connection.js:61:60)\n    at MessageStream.emit (node:events:513:28)\n    at MessageStream.emit (node:domain:489:12)\n    at processIncomingData (/backend/node_modules/mongodb/lib/cmap/message_stream.js:124:16)\n    at MessageStream._write (/backend/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:391:12)\n    at _write (node:internal/streams/writable:332:10)\n    at MessageStream.Writable.write (node:internal/streams/writable:336:10)\n    at Socket.ondata (node:internal/streams/readable:754:22)","ok":0,"code":18,"codeName":"AuthenticationFailed","connectionGeneration":0},"msg":"Unable to establish database connection"}
/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186
          const err = new MongooseError(message);
                      ^

MongooseError: Operation `secrets.updateMany()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/backend/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:186:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
```

**Comment by lightcycleresearch** [comment]
In the docker-compose file for mongo, the environmental vars aren't reading from the `.env` file

So you have to do something like:
```diff
  mongo:
    image: mongo
    restart: always
    env_file: .env
-    environment:
-      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
-      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
```

And in the `.env` file:
```diff
- MONGO_USERNAME=root
- MONGO_PASSWORD=mymongopassword
+ MONGO_INITDB_ROOT_USERNAME=root
+ MONGO_INITDB_ROOT_PASSWORD=mymongopassword
```

**Comment by maidul98** [comment]
Great catch @lightcycleresearch, I have updated to the docker compose to include `env_file: .env`

**Comment by akhilmhdh** [comment]
Closing as stale

**Comment by PeS82** [comment]
This must have been closed by mistake. The Mongo problem was not the original issue. The issue is with connection to Redis that is password protected (`requirepass`). 

And the issue is still present as of today, trying to set `REDIS_PASSWORD` or `REDIS_AUTH` does not help, Infisical can't connect.

**Comment by nerdlich** [comment]
I am not able to get it to work with `requirepass`, I always get NOAUTH from redis which suggests that no password is being sent. As a workaround, I set up a second unprotected redis host (called infisical-redis) in the same network, and still got NOAUTH. Turns out, even when I configure `REDIS_URL=redis://infisical-redis:6379`, it still connects to the host `redis` if there is one. And the NOAUTH is sent from there. When I shut down `redis`, the connection to `infisical-redis` is successful. Please reopen this issue.

**Comment by eduardo-diaz-em** [comment]
@maidul98 Is there any update on this? We can't either use redis with password:

```
name: em-runtime

x-postgres-user: &postgres-user ${POSTGRES_USER:-postgres}
x-postgres-password: &postgres-password ${POSTGRES_PASSWORD:-postgres}
x-postgres-uri: &postgres-uri postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432
x-redis-password: &redis-password ${REDIS_PASSWORD:-redis}
x-keycloak-admin-username: &keycloak-admin-username ${KEYCLOAK_ADMIN:-keycloak}
x-keycloak-admin-password: &keycloak-admin-password ${KEYCLOAK_ADMIN_PASSWORD:-keycloak}

x-healthcheck-defaults: &healthcheck-defaults
  interval: 10s
  timeout: 5s
  retries: 5

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: *postgres-user
      POSTGRES_PASSWORD: *postgres-password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *postgres-user]
      <<: *healthcheck-defaults
    configs:
      - source: psql_config
        target: /docker-entrypoint-initdb.d/initdb.sql
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8.4-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: *redis-password
    command: ["redis-server", "--requirepass", *redis-password]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", *redis-password, "ping"]
      <<: *healthcheck-defaults
    volumes:
      - redis-data:/data

  infisical:
    image: infisical/infisical:v0.155.5
    environment:
      ENCRYPTION_KEY: ${INFISICAL_ENCRYPTION_KEY:-f13dbc92aaaf86fa7cb0ed8ac3265f47}
      AUTH_SECRET: ${INFISICAL_AUTH_SECRET:-5lrMXKKWCVocS/uerPsl7V+TX/aaUaI7iDkgl3tSmLE=}
      DB_CONNECTION_URI: *postgres-uri
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: *redis-password
      SITE_URL: ${INFISICAL_SITE_URL:-http://localhost:8082}
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

configs:
  psql_config:
    content: |
      CREATE DATABASE infisical;

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
```

We get this error:

```
{"level":50,"time":1768563968066,"pid":1,"hostname":"3c549445b00d","severity":"ERROR","err":{"type":"ReplyError","message":"NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (/backend/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/backend/node_modules/redis-parser/lib/parser.js:302:14)","command":{"name":"info","args":[]}},"msg":"NOAUTH Authentication required."}
```
