### ISSUE TITLE
`INVITE_ONLY_SIGNUP`=`true` is ignored for GitHub

### ISSUE THREAD

**Issue by nbarrow-inspire-labs** [Infisical/infisical#1207]
### Describe the bug
When the environment variable is `INVITE_ONLY_SIGNUP` is set to `true`, new accounts can still be created if the `Continue with GitHub` button is configured and clicked.

### To Reproduce
1. Set `CLIENT_ID_GITHUB_LOGIN` and `CLIENT_SECRET_GITHUB_LOGIN` to valid OAuth values from GitHub
2. Set `INVITE_ONLY_SIGNUP` to `true`
3. Now, if you attempt to login using a GitHub account (i.e., one that has never been used on the infisical instance before) you are still authenticated, able to create an organization, reach the dashboard, etc.

### Expected behavior
Setting `INVITE_ONLY_SIGNUP` = `true` should block *all* account sign-ups, not just the manual email/password ones.

### Screenshots
n/a

### Platform you are having the issue on:
- Docker build: `infisical/infisical:v0.41.1`

### Additional context
n/a

**Comment by akhilmhdh** [comment]
@nbarrow-inspire-labs we have changed this behavoir recently. Use the latest image and you will have an administrator account flow. 

After that in the admin panel you can disable invite sign up. Then onwards nobody can do a signup

**Comment by mtracz** [comment]
@akhilmhdh 
Hi, I have a similar issue but for "email" signup flow on **self-hosted** instance.

`INVITE_ONLY_SIGNUP=true` is set but users can still create new accounts with new organizations. 
In admin panel `Enable signup or invite` is enabled.

I'm using `image: infisical/infisical:latest` (see docker-compose.yml).

<details>
<summary>docker-compose.yml</summary>
<br>

```yml
version: "3"

services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      - mongo
    image: infisical/infisical:latest
    env_file: .env
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
    networks:
      - infisical

  redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - infisical
    volumes:
      - redis_data:/data

  mongo:
    container_name: infisical-mongo
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - infisical
      
  mailpit:
    image: axllent/mailpit:v1.6.9
    ports:
      - 8025:8025
    networks:
      - infisical
    

volumes:
  mongo-data:
    driver: local
  redis_data:
    driver: local

networks:
  infisical:
```

</details>

<details>
<summary>.env</summary>
<br>

```dotenv
# Keys
# Required key for platform encryption/decryption ops
# THIS IS A SAMPLE ENCRYPTION KEY AND SHOULD NEVER BE USED FOR PRODUCTION
ENCRYPTION_KEY=6c1fe4e407b8911c104518103505b218

# JWT
# Required secrets to sign JWT tokens
# THIS IS A SAMPLE AUTH_SECRET KEY AND SHOULD NEVER BE USED FOR PRODUCTION
AUTH_SECRET=5lrMXKKWCVocS/uerPsl7V+TX/aaUaI7iDkgl3tSmLE=

# MongoDB
# Backend will connect to the MongoDB instance at connection string MONGO_URL which can either be a ref
# to the MongoDB container instance or Mongo Cloud
# Required
MONGO_URL=mongodb://root:example@mongo:27017/?authSource=admin

# Redis
REDIS_URL=redis://redis:6379

# Optional credentials for MongoDB container instance and Mongo-Express
MONGO_USERNAME=root
MONGO_PASSWORD=example

# Website URL
# Required
SITE_URL=http://localhost:80

INVITE_ONLY_SIGNUP=true

# Mail/SMTP 
SMTP_HOST=mailpit
SMTP_PORT=1025
SMTP_NAME=test-smtp
SMTP_USERNAME=null
SMTP_PASSWORD=null

# Integration
# Optional only if integration is used
CLIENT_ID_HEROKU=
CLIENT_ID_VERCEL=
CLIENT_ID_NETLIFY=
CLIENT_ID_GITHUB=
CLIENT_ID_GITLAB=
CLIENT_ID_BITBUCKET=
CLIENT_SECRET_HEROKU=
CLIENT_SECRET_VERCEL=
CLIENT_SECRET_NETLIFY=
CLIENT_SECRET_GITHUB=
CLIENT_SECRET_GITLAB=
CLIENT_SECRET_BITBUCKET=
CLIENT_SLUG_VERCEL=

# Sentry (optional) for monitoring errors
SENTRY_DSN=

# Infisical Cloud-specific configs
# Ignore - Not applicable for self-hosted version
POSTHOG_HOST=
POSTHOG_PROJECT_API_KEY=

# SSO-specific variables
CLIENT_ID_GOOGLE_LOGIN=
CLIENT_SECRET_GOOGLE_LOGIN=

CLIENT_ID_GITHUB_LOGIN=
CLIENT_SECRET_GITHUB_LOGIN=

CLIENT_ID_GITLAB_LOGIN=
CLIENT_SECRET_GITLAB_LOGIN=
```

</details>


<details>
<summary>Admin panel settings</summary>

![image](https://github.com/Infisical/infisical/assets/22484267/0cf2976d-46b0-4ccf-820b-d6f43c432267)

</details>

App: `http://localhost`
SMTP dashboard: `http://localhost:8025`

Is something misconfigured or this bug has not been fixed yet?

Expected behavior:
I would like to allow only invited users to create accounts/login into via email flow.
Other sing-ups for non invited users should be rejected.
