### ISSUE TITLE
401 issue with Kubernetes operator

### ISSUE THREAD

**Issue by Tchoupinax** [Infisical/infisical#1309]
### Describe the bug
Using the operator, the secret is not created because of receving a 401. The back also display the 401.

### To Reproduce
1. Create a new project
2. Create a single secret at the root
3. Create a service token for the new project, read only, unlimited duration
4. Setup the operator correctly and the InfisinicalSecret (secret is good, namespace is good, etc...)

```
{"level":30,"time":1705530410207,"pid":1,"hostname":"infisical-backend-b499cfc8f-vrwv2","severity":"INFO","msg":{"_logLevel":30,"_logName":"INFO","statusCode" │
│ :401,"type":"unauthorized","context":{},"extra":[],"stacktrace":["Error: You are not authorized to access this resource","    at UnauthorizedRequestError (/ba ││ ckend/build/utils/errors.js:55:12)","    at /backend/build/utils/authn/authModeValidators/serviceTokenV2.js:25:53","    at Generator.next (<anonymous>)","     │
│ at fulfilled (/backend/build/utils/authn/authModeValidators/serviceTokenV2.js:5:58)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (n ││ ode:internal/process/task_queues:96:5)"]}}
```

Operator: `v0.3.3`
Infisical backend: `v0.43.13`

**Comment by Tchoupinax** [comment]
```
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: prod
        secretsPath: /
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: cert-manager
  hostAPI: https://<MY_DOMAIN>/api
  managedSecretReference:
    secretName: my-secret-name
    secretNamespace: cert-manager
    secretType: Opaque
  resyncInterval: 60
```

**Comment by Tchoupinax** [comment]
```
apiVersion: v1
data:
  infisicalToken: base64
kind: Secret
metadata:
  name: my-secret-name
  namespace: cert-manager
type: Opaque
```
