### ISSUE TITLE
Issues with signup, INVITE_ONLY_SIGNUP env variable does not work

### ISSUE THREAD

**Issue by Mark24Slides** [Infisical/infisical#1321]
### Describe the bug
**Signup via invite does not work.**
Using latest self-hosted infisical/backend and infisical/frontend: v0.43.16

Sent invite to the user via Organization Access Control.
College opened the link, entered credentials and got: "Signup are disabled" respond.
 
![image](https://github.com/Infisical/infisical/assets/136308358/194295ee-adb7-462b-b6b2-9ffdba29d7cd)

INVITE_ONLY_SIGNUP env variable is setup with "true" (tried "false", with redeployment, same error).

![image](https://github.com/Infisical/infisical/assets/136308358/0222ff4e-209f-4f82-9d0a-e68a7b9ce6f6)

### To Reproduce
1. Go to Organization Access Control and create invite.
2. Open link, received via invite
3. Enter first and last name, password
4. See 400 error

### Platform you are having the issue on:
Kubernetes cluster, v.1.26

Docker images:
infisical/backend:v0.43.16
infisical/frontend:v0.43.16
infisical/kubernetes-operator:v0.3.3
gcr.io/kubebuilder/kube-rbac-proxy:v0.15.0
docker.io/bitnami/redis:7.2.3-debian-11-r1

P.S. Checked https://infisical.com/docs/self-hosting/configuration/envars, all should be ok (infisical works correctly, except signup).

**Comment by mtracz** [comment]
Hi, I have the same issue on **self-hosted** instance.

`INVITE_ONLY_SIGNUP=true` is set but random users can still create new accounts with new organizations via signup link on login page. 

In admin panel `Enable signup or invite` is enabled. 
If I disable it then got `Signup are disabled` in the response with 400 http code on POST /singupinvite route, but also link for signup disappears on login page then which is fine but invitations stop work then.

I'm using `image: infisical/infisical:v0.43.16` (see docker-compose.yml).

<details>
<summary>docker-compose.yml</summary>
<br>

```yml
version: "3"

services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      - mongo
    image: infisical/infisical:v0.43.16
    env_file: .env
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
    networks:
      - infisical

  redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - infisical
    volumes:
      - redis_data:/data

  mongo:
    container_name: infisical-mongo
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - infisical
      
  mailpit:
    image: axllent/mailpit:v1.6.9
    ports:
      - 8025:8025
    networks:
      - infisical
    

volumes:
  mongo-data:
    driver: local
  redis_data:
    driver: local

networks:
  infisical:
```

</details>

<details>
<summary>.env</summary>
<br>

```dotenv
# THIS IS A SAMPLE ENCRYPTION KEY AND SHOULD NEVER BE USED FOR PRODUCTION
ENCRYPTION_KEY=6c1fe4e407b8911c104518103505b218

# THIS IS A SAMPLE AUTH_SECRET KEY AND SHOULD NEVER BE USED FOR PRODUCTION
AUTH_SECRET=5lrMXKKWCVocS/uerPsl7V+TX/aaUaI7iDkgl3tSmLE=

MONGO_URL=mongodb://root:example@mongo:27017/?authSource=admin

REDIS_URL=redis://redis:6379

MONGO_USERNAME=root
MONGO_PASSWORD=example

SITE_URL=http://localhost:80

INVITE_ONLY_SIGNUP=true

# Mail/SMTP 
SMTP_HOST=mailpit
SMTP_PORT=1025
SMTP_NAME=test-smtp
SMTP_USERNAME=null
SMTP_PASSWORD=null
```

</details>


<details>
<summary>Admin panel settings</summary>

![image](https://github.com/Infisical/infisical/assets/22484267/0cf2976d-46b0-4ccf-820b-d6f43c432267)

</details>

App: `http://localhost`
SMTP dashboard: `http://localhost:8025`

Expected behavior:
I would like to allow only invited users to create accounts/login into via email flow.
Other sing-ups for non invited users should be rejected.

===
@Mark24Slides "in admin dashboard" do you have enabled or disabled `Enable signup or invite`?
You probably have disabled `Enable signup or invite` in admin dashboard. If you enable it, invitations will work, but also random users can create accounts and organizations.
