### ISSUE TITLE
I dont understand your documentation

### ISSUE THREAD

**Issue by Adityaudi** [Infisical/infisical#1327]
### Describe the bug
i dont undertand in your docs, what this is ...
![image](https://github.com/Infisical/infisical/assets/69835381/85f7bf5c-02bb-497c-9ebf-dd48308a0e66)

in article https://infisical.com/docs/integrations/platforms/kubernetes

**Comment by maidul98** [comment]
`...` means the rest of the example from the full example:

```
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret-sample
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: dev
        secretsPath: "/"
  managedSecretReference:
    secretName: managed-secret # <-- the name of kubernetes secret that will be created
    secretNamespace: default # <-- where the kubernetes secret should be created
```
