### ISSUE TITLE
[Helm Chart] Insufficient secrets-operator authorizations to sync secrets in other namespaces

### ISSUE THREAD

**Issue by CamilleHbp** [Infisical/infisical#1395]
### Describe the bug
I have a secret token created for glob path `/**` in dev environment, and the following command succeeds `infisical secrets --token=st.my_secret_token --env=dev --path=/my/app_path --domain=https://app.infisical.com/api`

In my k8s cluster, where the secrets-operator is installed and works (previous secret had no problem), I get the following error for my secret :

```yaml
status:
  conditions:
    - lastTransitionTime: '2024-02-12T15:41:03Z'
      message: >-
        Infisical controller has located the Infisical token in provided
        Kubernetes secret
      reason: OK
      status: 'True'
      type: secrets.infisical.com/LoadedInfisicalToken
    - lastTransitionTime: '2024-02-12T15:41:03Z'
      message: >-
        Failed to sync secrets. This can be caused by invalid service token or
        an invalid API host that is set. Check operator logs for more info
      reason: Error
      status: 'False'
      type: secrets.infisical.com/ReadyToSyncSecrets
    - lastTransitionTime: '2024-02-12T15:41:03Z'
      message: >-
        Auto redeployment has been stopped because the operator failed to sync
        secrets
      reason: Stopped
      status: 'False'
      type: secrets.infisical.com/AutoRedeployReady
```
### To Reproduce

This is my cluster setup, simplified

##### Infisical chart
```yaml
apiVersion: v2
name: infisical
description: Secret manager for Kubernetes
type: application
version: 0.1.0
appVersion: v0.1.0

dependencies:
  - name: secrets-operator
    version: v0.3.3
    repository: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
```

I use the following values to customize the Infisical helm chart:
```yaml
secrets-operator:
  controllerManager:
    replicas: 1
  kubernetesClusterDomain: cluster.local
  metricsService:
    ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: https
    type: ClusterIP
```

##### Infisical secret definition in chart templates
```yaml
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: app-env-token
  namespace: my-app-namespace
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: dev
        secretsPath: "/my/app_path"
      serviceTokenSecretReference:
        secretName: infisical-secret-token
        secretNamespace: tools
  hostAPI: 'https://app.infisical.com/api'
  managedSecretReference:
    secretName:  app-env-token
    secretNamespace: my-app-namespace
  ```
#### **my-app-namespace** namespace

There is an app deployment that uses 

```yaml
envFrom:
  - secretRef:
    name: app-env-token
```

### Platform you are having the issue on:
Managed kubernetes cluster (kubernetes v1.28.2)
