### ISSUE TITLE
YAML-based secret files

### ISSUE THREAD

**Issue by assembly-winston** [Infisical/infisical#1522]
### Feature description
A YAML-based env file to group related env variables together.

### Why would it be useful?
In my experience, when exporting the env file, the env file is not sorted in a logical way. I would organize the env file with comments to delineate, but then when fetching a new update, it will override it and I have to re-sort.

### Additional context
I am aware there is an option to export to yaml currently, but it is almost no different than exporting to .env. Rather, the .yaml export should group by tag on infisical, so three env vars with a similar tag would be together. e.g.

```
secrets:
    GitHub: // the tag
        GITHUB_CLIENT_SECRET: 'yadayada'
        GITHUB_CLIENT_ID: 'loremipsum'
```

Even more ideally, there'd be an option to remove common letters, e.g. the `GITHUB` in the above env, so reading could be done like `yamlFile["GitHub"]["CLIENT_SECRET]` (once unmarshaled)
