### ISSUE TITLE
[K8S/secret-operator] Allow a single service-token inside the secret-operator namespace / Allow Secret creation in a different namespace

### ISSUE THREAD

**Issue by CamilleHbp** [Infisical/infisical#1531]
### Feature description

As of the latest version, Infiscal requires the _InfisicalSecret_ to be deployed in the same namespace as the _Secret_ it will create. I think this is to avoid GitOps tools, such as ArgoCD, to delete the _Secret_. But Infisical also requires the auth service token _Secret_ to be set in the same namespace as the _InfisicalSecret_

 Feature requests:
1. Allow the _InfiscalSecret_ to create its secret in a different namespace.
> The [kubernetes-reflector](https://github.com/EmberStack/kubernetes-reflector) operator is able to reflect secrets in multiple namespaces without ArgoCD deleting them
2. Allow the secret-operator to use a single auth service token secret inside its own namespace.

### Why would it be useful?

The user is required to share their auth service token _Secret_ in all applications' namespaces in the current version of the _secret-operator_. This is a security concern.

It would also be a nice feature to allow the user to centralise all secret management in a single namespace if they like, by allowing a _Secret_ to be created in another namespace than the _InfisicalSecret_.
That also means that all user applications have access to my service token, which I do not find very safe. I would rather have the Infisical namespace be the only thing that can access my service token. :perplexe: I guess it might not be technically easy to do.

**Comment by dramirez-bluon** [comment]
Very important feature in my opinion. +1

**Comment by barthofu** [comment]
Totaly agree!

I have some problems with ArgoCD due to this... How can i get an effective workaround for the moment?

**Comment by CamilleHbp** [comment]
@barthofu You need to set the **creationPolicy** to **Owner** in your **InfisicalSecret**, and to have the **InfisicalSecret** in the same namespace as the **secrets-operator**. 

I user the emberstack's reflector to reflect the created secret in my application's namespace afterwards, using the annotations, since they are replicated on the created secret. You can see an example here.

This is my **InfisicalSecret**
```yaml
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: MyInfisicalSecret
  namespace: tools
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: MyAppNamespace # Control destination namespaces
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: MyAppNamespace # Control auto-reflection namespaces
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: same-namespace-as-infiscal # <-- where the service token secret should be. This needs to be the same namespace as infisical
      secretsScope:
        envSlug: myEnvSlug
        secretsPath: '/my/env/path'
  managedSecretReference:
    creationPolicy: "Owner" ##  <--  !!This is the important bit. You need to set the owner for ArgoCD, otherwise it will be automatically deleted!!
    secretName: MyEnvSecret # <-- the name of kubernetes secret that will be created
    secretNamespace: same-namespace-as-infiscal # <-- where the kubernetes secret should be created. This needs to be the same namespace as infisical
```
