### ISSUE TITLE
Integrations failing silently and other sync issues

### ISSUE THREAD

**Issue by asoc** [Infisical/infisical#1587]
### Describe the bug
1. If an integration fails there is no indication anywhere except a small "Failed to sync integrations" entry in the backend log. No root cause or any other details. 
2. If any integration fails but there are remaining integrations to sync they will not be executed.

I'm working strictly with GitHub at the moment but I believe this affects any integration.

### To Reproduce
1. Setup many integrations, including one with a repository that can be renamed or deleted and a secret that can be renamed or deleted.
2. Verify all integrations are syncing
3. Rename or delete a repository
4. Rename, add, or delete a secret, then check synced repositories and view the backend logs. Some repositories will sync while others will not.

Additionally I hit GitHubs rate limit while debugging this issue, which was also not visible without my logging additions (see the end of this issue).

### Expected behavior
All integrations that are able to be synced should sync regardless of if there is a failure in others.  
Any that fail should have their cause propogated to the UI, or at the very least into the logs.

### Screenshots

```json
{"level":30,"time":1710535639437,"pid":18,"hostname":"infisical-infisical-standalone-infisical-54bb88d9f-c7gp4","severity":"INFO","msg":"Secret integration sync started"}

snipped unrelated logs

{"level":50,"time":1710535639442,"pid":18,"hostname":"infisical-infisical-standalone-infisical-54bb88d9f-c7gp4","severity":"ERROR","msg":"Failed to sync integration"}
```

### Platform you are having the issue on:

Kubernetes / GitHub Integration

### Additional context

The inner code of this for-loop should have better error handling so that it can continue on failures: https://github.com/Infisical/infisical/blob/main/backend/src/services/secret/secret-queue.ts#L325

### Investigation process

This is the process I used to investigate the root cause, it would be nice to have some additional configurations or tooling available to make this easier:

1. Created a `ConfigMap` with a modified `/backend/dist/services/secret/secret-queue.mjs` that included some additional logging in the `toBeSyncedIntegrations` loop
2. Modified the Deployment to add these to the container spec:

```yaml
      command:
        - sh
        - '-c'
        - >-
          cp /patches/secret-queue.mjs
          /backend/dist/services/secret/secret-queue.mjs && npm start
      volumeMounts:
        - mountPath: /patches
          name: patches-vol
```

and this to the main deployment spec (required for the `cp` to work):

```yaml
  securityContext:
    runAsUser: 0
  volumes:
    - configMap:
        name: integration-sync-patches
      name: patches-vol
```

Once the new instance was running I deleted and added an integration to trigger the sync (would be nice to have an API endpoint for this)
