### ISSUE TITLE
Ability to use preexisting postgres server with infisical-standalone helm chart

### ISSUE THREAD

**Issue by mpsOxygen** [Infisical/infisical#1765]
### Feature description
I would like the ability to not only disable the installation of the postgres helm chart, but also be able to specify a secret from where to get an preexisting postgres server URI.

### Why would it be useful?
This would be useful when you don't want to install postgres along with infisical because you already have an existing postgres instance.

### Additional context
The existing postgres values would look like this:
```
postgresql:
  enabled: true
  name: "postgresql"
  fullnameOverride: "postgresql"
  auth:
    username: infisical
    password: root
    database: infisicalDB
  useExistingPostgres:
    # -- When this is enabled, postgresql.enabled needs to be false
    enabled: false
    # -- The name from where to get the existing postgresql connection URI
    existingUriSecret:
      # -- The name of the secret that contains the uri
      name: ""
      # -- Secret key name that contains the uri
      key: ""
```

And in the Deployment and Job template you would have something like this:
```
          env:
          {{- if .Values.postgresql.useExistingPostgres.enabled }}
          - name: DB_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.useExistingPostgres.existingUriSecret.name }}
                key: {{ .Values.postgresql.useExistingPostgres.existingUriSecret.key }}
          {{- end }}
```
