### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by 4F2E4A2E** [Infisical/infisical#1831]
Path: /integrations/platforms/docker-compose

First, let me thank you for infisical. I think it is a great open-source project and product. You guys rock 🚀 

The docker-compose integration is not working for me.

It appears that the mentioned requirement [docker-guide](https://infisical.com/docs/integrations/platforms/docker) is not in sync with the newly introduced machine-identity creds.

infisical is ignoring INFISICAL_MACHINE_IDENTITY_CLIENT_ID and INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET.

```Dockerfile
FROM alpine:latest

RUN apk add --no-cache bash curl && curl -1sLf \
'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
&& apk add infisical

```

```yaml
services:
  test:
    image: sha256:2e3 # alpine:latest
    environment:
      - MY_VAR="222"
      - INFISICAL_MACHINE_IDENTITY_CLIENT_ID=${INFISICAL_MACHINE_IDENTITY_CLIENT_ID_FOR_WEB}
      - INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET=${INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET_FOR_WEB}
    command: ["infisical", "run", "--projectId", "dedacted", "--path", "/dedacted", "--", "printenv"]
```

```bash
╰─⠠⠵ docker compose up     
[+] Running 2/0
 ✔ Network test_default   Created                                                                          0.0s 
 ✔ Container test-test-1  Created                                                                          0.0s 
Attaching to test-1
test-1  | It looks you have not yet connected this project to Infisical
test-1  | To do so, run [infisical init] then run your command again
test-1 exited with code 1
```
