### ISSUE TITLE
Self Host Getting Started

### ISSUE THREAD

**Issue by lee-aaron** [Infisical/infisical#1985]
I have a kubernetes cluster on DigitalOcean and am just running through the documentation with the [helm chart](https://infisical.com/docs/self-hosting/deployment-options/kubernetes-helm) to self host.

Don't know if it makes a difference but I have other services running behind traefik

Qs:
- What URL / endpoint should I be going to after installing? I see an IP for the infisical ingress when I run `kubectl get svc`
- I presume something like [this](https://infisical.com/docs/integrations/platforms/kubernetes#using-managed-secret-in-your-deployment) is how I could separate production / staging secrets?

Side Note: The slack url doesn't work for me for some reason. Keeps saying to make an account but I already have a slack account.

**Comment by Daemoen** [comment]
@lee-aaron The (exposed) endpoint would be dependent on how you configure your ingress.

As an example, the following is a definition that I use with an ALB controller on EKS:
```
ingress:
  enabled: true
  hostName: ${infisical_host_url} # I define this and load it into the template
  ingressClassName: alb
  nginx:
    enabled: false
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'

```

The controller maps the ALB to the target group, etc.  Once you deploy the chart, you should be able to check your service/ingress definitions and determine the endpoint.  Ultimately, you'll be pointing at the infisical-standalone service on port 8080.

If you use your own redis/postgres, as long as you have those values defined in the data, you should be good.

For the production/staging, the docs youre looking at are about how to consume the secrets and doesnt really get into separation.  For that, you will want to learn more about 'Environments' in infisical, which each environment has a corresponding Slug within a project.  See:  https://infisical.com/docs/documentation/platform/project

The slack url should be:  https://infisical-users.slack.com  If you already have a standard slack sign-in, you should be able to add that workspace.
