### ISSUE TITLE
Infisical behind Traefik

### ISSUE THREAD

**Issue by mvandenabeele** [Infisical/infisical#2045]
I have Infisical running as a portainer stack on an Ubuntu server. The stack is configured like this:

```
version: "3"

services:
  db-migration:
    container_name: infisical-db-migration
    env_file: stack.env
    depends_on:
      db:
        condition: service_healthy
    image: infisical/infisical:latest-postgres
    command: npm run migration:latest
    pull_policy: always
    networks:
      - infisical

  backend:
    container_name: infisical-backend
    restart: unless-stopped
    env_file: stack.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    image: infisical/infisical:latest-postgres
    pull_policy: always
    environment:
      - NODE_ENV=production
    networks:
      - infisical
      - traefik_public
    labels:
      - traefik.enable=true # enables the service
      - traefik.http.routers.infisical.rule=Host(`infisical.jabbla.com`) # domain to expose on
      - traefik.http.routers.infisical.entrypoints=websecure
      - traefik.http.routers.infisical.tls=true
      - traefik.http.routers.infisical.service=infisical
      - traefik.http.services.infisical.loadbalancer.server.port=8080
      - traefik.http.services.infisical.loadbalancer.server.scheme=http

  redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: stack.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - infisical
    volumes:
      - redis_data:/data

  db:
    container_name: infisical-db
    image: postgres:14-alpine
    env_file: stack.env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  infisical:
  traefik_public:
    external: true
```

Traefik is working well for other services running on this host, but Infisical is hit-or-miss. Sometimes it is not accessible and then I need to restart the stack a few times to get it working. I think it has something to do with the fact that the backend service is connected to two networks. Maybe the backend service is binding to only one random network interface? What can I do to fix this?

Kind regards,
Merijn
