### ISSUE TITLE
kubernetes operator .dockerconfigjson issue

### ISSUE THREAD

**Issue by maximehuylebroeck** [Infisical/infisical#2058]
### Describe the bug

When creating a secret with infisical kubernetes operator for .dockerconfigjson types it gives the following error in the operator: 
```unable to reconcile Infisical Secret because [err=unable to create the managed Kubernetes secret : Secret "dockerhub-secret" is invalid: data[.dockerconfigjson]: Required value]. Will requeue after [requeueTime=1m0s]```

Don't know if it is relevant but it doesn't say in the docs how to store the secret key nor does it say if the secret value plain text or base64? tried it with full plain text, full base64 only auth base64

small note other secrets are working fine so it's not the operator not being able to connect.

### To Reproduce
Though what i have right now:
infisical secret yaml 
```yaml
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-registry
  namespace: <namespace>
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-token
        secretNamespace: infisical
      secretsScope:
        projectSlug: <slug-here>
        envSlug: dev
        secretsPath: "/dockerhub" # stored in /dockerhub/.DOCKERCONFIGJSON
  managedSecretReference:
    secretName: dockerhub-secret
    secretNamespace: <namespace>
    creationPolicy: "Owner"
    secretType: "kubernetes.io/dockerconfigjson"
```
.dockerconfigjson that i pasted in the value of the secret in infisical:
```json
{"auths":{"https://index.docker.io/v1/":{"auth":"username:token"}}}
```

### Expected behavior
It creates a secret of type dockerconfigjson with the correct key and value

### Platform you are having the issue on:
kubernetes  + helm chart of operator
