### ISSUE TITLE
universal method with kubernetes operator in a self hosted infisical app 

### ISSUE THREAD

**Issue by ygwane** [Infisical/infisical#2170]
### Describe the bug
I try to get universal auth method to work on a infisical app hosted in my kubernetes cluster. No problem to sync secret with service token method.
Documentation about kubernetes operator is not clear or I miss something ...

### To Reproduce
1. Install helm repository and update installed repos
2. Install helm chart with last published version on infisical namespace
3. Create identity on Infisical app and create a client secret into Universal Auth authentication method
4. Add this identity to project with developer role
5. Create a generic secret on kubernetes with client id and client secret like this: 
```
kubectl create secret generic infisical-secrets \
  --from-literal=client-id=********-****-****-****-************ \
  --from-literal=client-secret=********************************************************** \
  -n infisical
```
7. Create InfisalSecret with YAML manifest: 
```
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret
  namespace: infisical
spec:
  hostAPI: http://infisical-infisical-standalone-infisical:8080/api
  resyncInterval: 10
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: kubernetes-tk3r
        envSlug: dev
        secretsPath: "/"
        recursive: true
      credentialsRef:
        secretName: infisical-secrets
        secretNamespace: infisical
  managedSecretReference:
    secretName: managed-secret
    secretNamespace: infisical
    creationPolicy: "Orphan"
    # secretType: kubernetes.io/dockerconfigjson # Uncomment this if needed
```
9. Describe InfisicalSecret, display errors: 
```
Status:
  Conditions:
    Last Transition Time:  2024-07-24T08:51:14Z
    Message:               Failed to load Infisical Token from the provided Kubernetes secret because: no authentication method provided
    Reason:                Error
    Status:                False
    Type:                  secrets.infisical.com/LoadedInfisicalToken
    Last Transition Time:  2024-07-24T08:51:14Z
    Message:               Failed to sync secrets. This can be caused by invalid service token or an invalid API host that is set. Check operator logs for more info
    Reason:                Error
    Status:                False
    Type:                  secrets.infisical.com/ReadyToSyncSecrets
    Last Transition Time:  2024-07-24T08:51:14Z
    Message:               Auto redeployment has been stopped because the operator failed to sync secrets
    Reason:                Stopped
    Status:                False
    Type:                  secrets.infisical.com/AutoRedeployReady
Events:                    <none>
```
11. Check operator pod logs, get error: 
```
Manual re-sync interval set. Interval: 10s
ReconcileInfisicalSecret: No authentication strategy found. Attempting to authenticate
unable to reconcile Infisical Secret because [err=unable to authenticate [err=no authentication method provided]]. Will requeue after [requeueTime=10s]

Manual re-sync interval set. Interval: 10s
ReconcileInfisicalSecret: No authentication strategy found. Attempting to authenticate
unable to reconcile Infisical Secret because [err=unable to authenticate [err=no authentication method provided]]. Will requeue after [requeueTime=10s]
```
14. Try to delete operator pod: same issue.

### Expected behavior
Get Infisical secret object to sync app secrets from Infisical project to kubernetes secret called managed-secret.

### Platform you are having the issue on:
Self hosted Infisical app on kubernetes cluster, helm install.
