### ISSUE TITLE
Failed to create first admin user. Not able to use the product

### ISSUE THREAD

**Issue by gs-kug** [Infisical/infisical#2259]
### Describe the bug
Installed infisical in Kubernetes following official docs.
Accessing application using custom gateway with SSL certificate.
No able to create the user.
Tried with port-forward same error. Tried enable github authentication, same erro (it does not authenticate with github, keeps asking to create user)

### To Reproduce
Check the video
https://1drv.ms/v/s!AoHvV-Rb6N9QiLhTQBip3L5Swsq87w?e=p2jrap

### Expected behavior
After a successful installation create the admin user should work
### Platform you are having the issue on:
Kubernetes

**Comment by Ayush-Dutt-Sharma** [comment]
@akhilmhdh can i take this

**Comment by akhilmhdh** [comment]
@gs-kug kindly check your server log and networking.

The admin user is not getting created because of some infra issues

**Comment by gs-kug** [comment]
There is no  significant log error
The browser has errors with Security-Policy:

ontent-Security-Policy: The page’s settings blocked the loading of a resource (connect-src) at https://us-c.i.posthog.com/i/v0/e/?compression=gzip-js&ip=1&_=1723299010244&ver=1.105.6&retry_count=1 because it violates the following directive: “connect-src 'self' wss://nexus-websocket-a.intercom.io https://api-iam.intercom.io/ https://api.heroku.com/ https://id.heroku.com/oauth/authorize https://id.heroku.com/oauth/token https://checkout.stripe.com/ https://app.posthog.com/ https://api.stripe.com/ https://api.pwnedpasswords.com/ http://127.0.0.1:* https://hcaptcha.com/ [https://*.hcaptcha.com](https://%2A.hcaptcha.com/)” [_app-3ab697c139afc494.js:1:620219](https://infisical.kugelbit.work/_next/static/chunks/pages/_app-3ab697c139afc494.js)
Content-Security-Policy: The page’s settings blocked the loading of a resource (connect-src) at https://us-c.i.posthog.com/i/v0/e/?compression=gzip-js&ip=1&_=1723299022529&ver=1.105.6 because it violates the following directive: “connect-src 'self' wss://nexus-websocket-a.intercom.io https://api-iam.intercom.io/ https://api.heroku.com/ https://id.heroku.com/oauth/authorize https://id.heroku.com/oauth/token https://checkout.stripe.com/ https://app.posthog.com/ https://api.stripe.com/ https://api.pwnedpasswords.com/ http://127.0.0.1:* https://hcaptcha.com/ [https://*.hcaptcha.com](https://%2A.hcaptcha.com/)”

Is this some kind of catcha that is malfunctioning?

**Comment by gs-kug** [comment]
I found the problem:

I change the config from:

```
nameOverride: "infisical"
fullnameOverride: "infisical"
infisical:
  image:
    repository: infisical/infisical
    tag: "v0.78.1-postgres"
    pullPolicy: IfNotPresent
  autoDatabaseSchemaMigration: true
  name: infisical
  fullnameOverride: ""
  replicaCount: 3
  kubeSecretRef: "infisical-secrets"
  resources:
    limits:
      memory: 210Mi
    requests:
      cpu: 200m
ingress:
  enabled: true
  hostName: "infisical.kugelbit.work"
postgresql:
  enabled: false
redis:
  enabled: false
```

To:

```
nameOverride: "infisical"
fullnameOverride: "infisical"
infisical:
  image:
    repository: infisical/infisical
    tag: "v0.78.1-postgres"
    pullPolicy: IfNotPresent
  autoDatabaseSchemaMigration: true
  name: infisical
  replicaCount: 2
  kubeSecretRef: "infisical-secrets"
  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 200m
ingress:
  enabled: false
  hostName: "infisical.kugelbit.work"
postgresql:
  enabled: false
redis:
  enabled: false
```

Diff: memory, replicaCount, fullnameOverride, ingress (I'm using custom ingress)

I'm not sure where is the problem as I change all at once. Maybe the memory but there is no log end container restart
