### ISSUE TITLE
K8s Operator v0.7.0 not working on self hosted environments

### ISSUE THREAD

**Issue by MohamadTahir** [Infisical/infisical#2272]
### Describe the bug
Hello, the operator is not working on self hosted environment as it is always calling the cloud infisical, it does not respect the global configuration configMap. 

### To Reproduce
1. deploy infisical on your k8s cluster,  
2. create and deploy the following configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-config
  namespace: infisical-operator-system
data:
  hostAPI: https://your.infisical.endpoint/api
```

3. deploy your infisical operator on a k8s cluster
4. create an infisical secret
5. check the operator logs and you'll see that the requests are being sent to 
```
https://app.infisical.com/api.......
```
### Expected behavior
send the request to the configured endpoint in the configmap
