### ISSUE TITLE
Extend Secret templating for InfisicalSecret

### ISSUE THREAD

**Issue by tiagovtristao** [Infisical/infisical#2398]
### Feature description

We are currently using ArgoCD and a GitOps approach and would benefit if the `Secret` generated by the `InfisicalSecret` could be further customised. At the moment, we have to manually populate the `sshPrivateKey` below:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: tortus-repo-access-secret
  namespace: argocd
  labels:
      argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:tortus-ai/foobar.git
  sshPrivateKey: # (to-be-filled)
```

Would it be possible/feasible for the `InfisicalSecret` to generate a `Secret` as above and have certain fields (`sshPrivateKey` in this case) auto populated via some mapping/placeholder?

### Why would it be useful?

This would allow for any Secret template to be handled by the Infisical's K8s operator and not having to manually update some of them. This would also make it more GitOps-compatible.
