### ISSUE TITLE
[External Secret] - Can't read a secret from a folder

### ISSUE THREAD

**Issue by Tchoupinax** [Infisical/infisical#2469]
Hello!

### Describe the bug
I have an opened issue when I want to take a secret from a folder with External Secret.

- I can read a secret located at root
- I can read all secrets (recursively) with a regex
- I get an error when I want to target a deep secret ([associated issue](https://github.com/external-secrets/external-secrets/issues/3938#issuecomment-2367677014))

### Expected behavior
I expect to be able to get a secret in a specific folder

I ask your help about this, I don't know exactly if it comes from Infisical or External Secret

Infisical version: `v0.85.0-postgres`

**Comment by akhilmhdh** [comment]
To access secret inside a folder you need to change the secretPath property in Infisical auth store of external secret operator?

**Comment by Tchoupinax** [comment]
So I have to create a store for every folder? I can't allow a store to access all secrets recursively?
The feature is cool on security side but in this case having a store accessing all project's secrets is OK.

**Comment by akhilmhdh** [comment]
@Tchoupinax This is how external secrets operator is designed. The issue with if you apply recursive in store level is you can't control which folder to be show. It will always pull recursively.

**Comment by 6ixfalls** [comment]
@akhilmhdh, a way this could be implemented is using both the remoteRef key and property values. My existing implementation with Infisical is through a webhook SecretStore, which looks as such (prior to machine identities):
<details>
<summary>Kubernetes Resource</summary>

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    webhook:
      url: "${infisicalURL}api/v3/secrets/raw/{{ .remoteRef.property }}?environment={{ .conf.environment }}&workspaceId={{ .conf.workspaceId }}&secretPath=/{{ .remoteRef.key }}"
      method: GET
      timeout: 5s
      result:
        jsonPath: "$.secret.secretValue"
      headers:
        Authorization: "Bearer {{ .conf.infisicalToken }}"
      secrets:
        - name: conf
          secretRef:
            name: cluster-secrets
            namespace: flux-system
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical-full
spec:
  provider:
    webhook:
      url: "${infisicalURL}api/v3/secrets/raw/{{ .remoteRef.property }}?environment={{ .conf.environment }}&workspaceId={{ .conf.workspaceId }}&secretPath=/{{ .remoteRef.key }}"
      method: GET
      timeout: 5s
      result: {}
      headers:
        Authorization: "Bearer {{ .conf.infisicalToken }}"
      secrets:
        - name: conf
          secretRef:
            name: cluster-secrets
            namespace: flux-system
```
The first allows for individual secrets to be accessed, while the the second allows for arbitrary secret population. The key specifies the path to the secret(s) while the property is the value itself.
</details>

The current Infisical External Secrets Operator doesn't hit my use-case for Infisical, which is the easy sorting and organization of secrets within a project using folders. It would be ideal to not have to use these workarounds, but I prefer to use external-secrets over the native Infisical operator.

**Comment by akhilmhdh** [comment]
@6ixfalls I am unsure how the above would fit in external secrets operator design

**Comment by crstian19** [comment]
Is this working after this https://github.com/external-secrets/external-secrets/pull/3939? @Tchoupinax can you give me an example? I've tried everything and still can't get it to work.

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: infisical-managed-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore  
    name: infisical          
  target:
    name: immich-secret      
  dataFrom:
  - extract:
      key: immich    # infisical folder name
```

**Comment by jorgeecardona** [comment]
@crstian19 is not working for me, I am on Kubernetes v1.32.0 and the operator version 0.14.0

**Comment by Adriien-M** [comment]
@jorgeecardona I tried this syntax with v0.14.2 saldy it doesn't load any secret :'(

**Comment by clementblaise** [comment]
Confirming what @Adriien-M is seeing, it only works with a wildcard:
```yaml
  dataFrom:
    - find:
        name:
          regexp: .*
```
It will return all secrets without the full path, only the key. Thats means folder are not usable which kind of make the provider useless.

> @akhilmhdh This is how external secrets operator is designed

It's more how this provider was implemented, not external secrets as whole. If you look at [AWS Secret Manager implementation](https://external-secrets.io/latest/provider/aws-secrets-manager/) that's the input for a JSON object:
```yaml
data:
  - secretKey: my_name
    remoteRef:
      key: friendslist
      property: name.first
``` 
The key also supports path like notation:
```yaml
data:
  - secretKey: previous-api-key
    remoteRef:
      key: "production/api-key"
      version: "AWSPREVIOUS"
```
AWS Secret Manager doesn't have a folder structure but it allows having policies based on the path like notation.

Thank you @6ixfalls for providing the webhook, it's exactly how I intended to use it as well
