### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by golemboy** [Infisical/infisical#2581]
Path: /integrations/platforms/docker-compose

I've searched for hours, but you don't mention leaving the env variable secret in the docker compose file.

```
# Example Docker Compose file
services:
  web:
    build: .
    image: example-service-1
    environment:
      - INFISICAL_MACHINE_IDENTITY_CLIENT_ID=${INFISICAL_MACHINE_IDENTITY_CLIENT_ID_FOR_WEB}
      - INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET=${INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET_FOR_WEB}
      - MY_SECRET_VAR1 # secret var recorded in the secret store
      - MY_SECRET_VAR2 #secre var recorded in the secret store

  api:
    build: .
    image: example-service-2
    environment:
      - INFISICAL_MACHINE_IDENTITY_CLIENT_ID=${INFISICAL_MACHINE_IDENTITY_CLIENT_ID_FOR_API}
      - INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET=${INFISICAL_MACHINE_IDENTITY_CLIENT_SECRET_FOR_API}
      - MY_SECRET_VAR3 # secret var recorded in the secret store
      - MY_SECRET_VAR4 #secre var recorded in the secret store

```
