### ISSUE TITLE
Helm install breaks RBAC between versions 1.0.8 and 1.2.0

### ISSUE THREAD

**Issue by GameBurrow** [Infisical/infisical#2640]
### Describe the bug
After updating `infisical-standalone` helm from version 1.0.8 to 1.2.0 I noticed my infisical pod failed to start up after updating the image version.

Looking deeply the `infisical-standalone` pod failed to start because `migration-ini`t container threw the following error:
```
jobs.batch "infisical-schema-migration-1" is forbidden: User "system:serviceaccount:infisical:default" cannot get resource "jobs" in API group "batch" in the namespace "infisical"
```

Originally I didn't link my head that the issue was created by infisical-standalone helm update, tried a lot of different things before fiquring out the problem. It seems that there is some kind of rbac setup error in the later helm version as when I reverted the infisical-standalone helm version back to 1.0.8, everything started working again:
```yaml
    - repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
      targetRevision: 1.0.8 # Add repo locally and check latest with helm search repo infisical, look at chart version
      chart: infisical-standalone
      helm:
        releaseName: infisical
        valueFiles:
          - $repo1/values.yml
    
```
