### ISSUE TITLE
gitlab-ci will not pull correct environment

### ISSUE THREAD

**Issue by bylmzio** [Infisical/infisical#2763]
Hi there i am trying to deploy my Laravel Project through gitlab-ci.
On staging everything worked fine.
But on Production i have problems.
`infisical export --env=production > .env` will not pull production environments. 
It will some how pull the staging environments.
But it is working when i use my local terminal.

**Note: Production slug is set to 'production' and is not 'prod'

The whole gitlab stage:

```
build:npm:production:
  stage: build
  only:
    - production
  image: node:20-bullseye-slim
  needs:
    - build:php:production
  environment:
    name: production
  script:
    - npm install
    - apt update && apt install -y curl
    - curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | bash
    - apt-get update && apt-get install -y infisical
    - infisical run --env=production -- npm run build
    - infisical export --env=production > .env
  artifacts:
    expire_in: 10 mins
    paths:
      - ./
```
