### ISSUE TITLE
Cannot run Infisical in Docker Compose (both normal run and schema migration)

### ISSUE THREAD

**Issue by java-juggled-jazz** [Infisical/infisical#2843]
### Describe the bug
I've tried to run Infisical, PostgresQL and Redis using Docker Compose

```
version: "3.0"
services:
  infisical:
    container_name: infisical
    image: infisical/infisical:v0.96.1-postgres
    ports:
      - 80:80
      - 443:443
    environment:
      - DB_CONNECTION_URI=postgres
      - REDIS_URL=redis
      - SITE_URL=http://xxx.xxx.xxx.xxx
    env_file:
      - .infisical-env ## env-file contains encryption key and auth secret

  postgres:
    container_name: postgres
    image: postgres:13-bookworm
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
    env_file:
      - .postgres-env ## env-file contains Postgres password

  redis:
    container_name: redis
    image: redis:7.4-bookworm
    volumes:
      - ./redis-volume:/data
```

PostgresQL and Redis run normal, Infisical only have issues. `docker logs infisical` output:

```
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
Environment variable replacement is the same, skipping..
Telemetry is enabled
(node:1) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"level":50,"time":1733339008491,"pid":1,"hostname":"e2db3439158b","severity":"ERROR","err":{"type":"Error","message":"getaddrinfo ENOTFOUND base","stack":"Error: getaddrinfo ENOTFOUND base\n    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)","errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"base"},"msg":"getaddrinfo ENOTFOUND base"}
``` 

I know, there is a step with schema migration. Whenever I try to run migration using `docker run --env DB_CONNECTION_URI=postgresql://postgres:PASSWORD@postgres:PORT/infisical infisical/infisical:v0.96.1-postgres npm run migration:latest` I have this output:

```

> backend@1.0.0 migration:latest
> npm run auditlog-migration:latest && knex --knexfile ./src/db/knexfile.ts --client pg migrate:latest


> backend@1.0.0 auditlog-migration:latest
> knex --knexfile ./src/db/auditlog-knexfile.ts --client pg migrate:latest

Requiring external module ts-node/register
Working directory changed to /backend/src/db
Dedicated audit log database not found. No further migrations necessary
Requiring external module ts-node/register
Working directory changed to /backend/src/db
Using environment: production
getaddrinfo ENOTFOUND postgres
Error: getaddrinfo ENOTFOUND postgres
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.2
npm notice To update run: npm install -g npm@10.9.2
npm notice
```

### To Reproduce
1. Copy docker-compose.yml to your host
2. Type there your IP in SITE_URL 
3. Create .infisical-env with ENCRYPTION_KEY and AUTH_KEY, .postgres-env file POSTGRES_PASSWD
4. Run `docker compose up -d`
5. See error using `docker logs infisical` on host
6. See migration error using `docker run --env DB_CONNECTION_URI=postgresql://postgres:PASSWORD@postgres:PORT/infisical infisical/infisical:v0.96.1-postgres npm run migration:latest` on host

### Expected behavior
Infisical and its migration should run normal

### Platform you are having the issue on:
Docker version 27.3.1
Containers:
1. infisical:v0.96.1-postgres
2. postgres:13-bookworm
4. redis:7.4-bookworm

AlmaLinux 9.0, AMD64 (VM)
