### ISSUE TITLE
[K8s Operator] - New secret values not created on CRD update 

### ISSUE THREAD

**Issue by LonguCodes** [Infisical/infisical#2906]
### Describe the bug
After adding new values to be synched in the `InfisicalSecret` CRD (updating the manifest and applying) the operator does not update the K8s secret 

### To Reproduce
1. Add 2 secrets in Infisical
2. Create InfisicalSecret CRD, which uses 1 of the secrets
3. Wait for the k8s secret to be created
4. Add reference to the 2nd secret in the CRD and apply

### Expected behavior
K8s secret is applied

### Platform you are having the issue on:
Kubernetes deployment

**Comment by vanchaxy** [comment]
Encountered the same today when I updated the template in InfisicalSecret.

1. Created this secret.
```
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: authentik
spec:
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: homelab-vn-bd
        envSlug: prod
        secretsPath: "/authentik"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: authentik-secret
    secretNamespace: authentik
    template:
      data:
        AUTHENTIK_SECRET_KEY: '{{ `{{ .secret_key.Value }}` }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: '{{ `{{ .postgres_user_password.Value }}` }}'
```
2. Added `bootstrap_token` in `authentik` folder.
3. Waited a few minutes. InfisicalSecret has been refreshed, but the template has not yet changed, so there are no changes to kube secret.
4. Added ```AUTHENTIK_BOOTSTRAP_TOKEN: '{{ `{{ .bootstrap_token.Value }}` }}'``` to template.

Kubernetes secret never updates after that. After manually deleting `authentik-secret` secret, infisical created a new one with the new template.
