### ISSUE TITLE
role "infisical" does not exist

### ISSUE THREAD

**Issue by harshguptaserver** [Infisical/infisical#2934]
### Describe the bug
I am trying to run the infiscal service on a linux/ubuntu system using docker compose and getting this error : role "infisical" does not exist

Reference : https://infisical.com/docs/self-hosting/deployment-options/docker-compose

### To Reproduce
docker-compose.yml
```
version: "3"

services:
  db-migration:
    container_name: infisical-db-migration
    depends_on:
      db:
        condition: service_healthy
    image: infisical/infisical:latest-postgres
    env_file: .env
    command: npm run migration:latest
    pull_policy: always
    networks:
      - infisical

  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    image: infisical/infisical:latest-postgres
    pull_policy: always
    env_file: .env
    ports:
      - 80:8080
    environment:
      - NODE_ENV=production
    networks:
      - infisical

  redis:
    image: redis
    container_name: infisical-dev-redis
    env_file: .env
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - infisical
    volumes:
      - redis_data:/data

  db:
    container_name: infisical-db
    image: postgres:14-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  infisical:
```

.env
```
# Keys
# Required key for platform encryption/decryption ops
# THIS IS A SAMPLE ENCRYPTION KEY AND SHOULD NEVER BE USED FOR PRODUCTION
# Must be a random 16 byte hex string. Can be generated with openssl rand -hex 16
ENCRYPTION_KEY=1e75649ff39d6399761ced6ddcf6c2ed

# JWT
# Required secrets to sign JWT tokens
# THIS IS A SAMPLE AUTH_SECRET KEY AND SHOULD NEVER BE USED FOR PRODUCTION
# EXAMPLE = AUTH_SECRET=5lrMXKKWCVocS/uerPsl7V+TX/aaUaI7iDkgl3tSmLE=
# Must be a random 32 byte base64 string. Can be generated with openssl rand -base64 32
AUTH_SECRET=4D8IWxR05GPTvmIWPS8mEj3Lf2H40b6RQbKYz6SPAGY=


TELEMETRY_ENABLED = "false"

# Postgres creds
POSTGRES_PASSWORD=infisical
POSTGRES_USER=infisical
POSTGRES_DB=infisical

# Required
DB_CONNECTION_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

# Redis
REDIS_URL=redis://redis:6379

# Website URL
# Required
SITE_URL=http://localhost:8080

# Mail/SMTP 
SMTP_HOST=
SMTP_PORT=
SMTP_NAME=
SMTP_USERNAME=
SMTP_PASSWORD=

# Integration
# Optional only if integration is used
CLIENT_ID_HEROKU=
CLIENT_ID_VERCEL=
CLIENT_ID_NETLIFY=
CLIENT_ID_GITHUB=
CLIENT_ID_GITHUB_APP=
CLIENT_SLUG_GITHUB_APP=
CLIENT_ID_GITLAB=
CLIENT_ID_BITBUCKET=
CLIENT_SECRET_HEROKU=
CLIENT_SECRET_VERCEL=
CLIENT_SECRET_NETLIFY=
CLIENT_SECRET_GITHUB=
CLIENT_SECRET_GITHUB_APP=
CLIENT_SECRET_GITLAB=
CLIENT_SECRET_BITBUCKET=
CLIENT_SLUG_VERCEL=

CLIENT_PRIVATE_KEY_GITHUB_APP=
CLIENT_APP_ID_GITHUB_APP=

# Sentry (optional) for monitoring errors
SENTRY_DSN=

# Infisical Cloud-specific configs
# Ignore - Not applicable for self-hosted version
POSTHOG_HOST=
POSTHOG_PROJECT_API_KEY=

# SSO-specific variables
CLIENT_ID_GOOGLE_LOGIN=
CLIENT_SECRET_GOOGLE_LOGIN=

CLIENT_ID_GITHUB_LOGIN=
CLIENT_SECRET_GITHUB_LOGIN=

CLIENT_ID_GITLAB_LOGIN=
CLIENT_SECRET_GITLAB_LOGIN=

CAPTCHA_SECRET=

NEXT_PUBLIC_CAPTCHA_SITE_KEY=

OTEL_TELEMETRY_COLLECTION_ENABLED=false
OTEL_EXPORT_TYPE=prometheus
OTEL_EXPORT_OTLP_ENDPOINT=
OTEL_OTLP_PUSH_INTERVAL=

OTEL_COLLECTOR_BASIC_AUTH_USERNAME=
OTEL_COLLECTOR_BASIC_AUTH_PASSWORD=

PLAIN_API_KEY=
PLAIN_WISH_LABEL_IDS=

SSL_CLIENT_CERTIFICATE_HEADER_KEY=

ENABLE_MSSQL_SECRET_ROTATION_ENCRYPT=true

# App Connections

# aws assume-role
INF_APP_CONNECTION_AWS_ACCESS_KEY_ID=
INF_APP_CONNECTION_AWS_SECRET_ACCESS_KEY=

# github oauth
INF_APP_CONNECTION_GITHUB_OAUTH_CLIENT_ID=
INF_APP_CONNECTION_GITHUB_OAUTH_CLIENT_SECRET=

#github app
INF_APP_CONNECTION_GITHUB_APP_CLIENT_ID=
INF_APP_CONNECTION_GITHUB_APP_CLIENT_SECRET=
INF_APP_CONNECTION_GITHUB_APP_PRIVATE_KEY=
INF_APP_CONNECTION_GITHUB_APP_SLUG=
INF_APP_CONNECTION_GITHUB_APP_ID=
```
### Expected behavior
it should work

### log

```
docker compose up
WARN[0000] ./infiscal_kms/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 2/2
 ✔ db-migration Pulled                                                                                                                                                                   2.9s 
 ✔ backend Pulled                                                                                                                                                                        2.9s 
[+] Running 4/2
 ✔ Container infisical-db            Created                                                                                                                                             0.1s 
 ✔ Container infisical-dev-redis     Created                                                                                                                                             0.1s 
 ✔ Container infisical-db-migration  Created                                                                                                                                             0.0s 
 ✔ Container infisical-backend       Created                                                                                                                                             0.0s 
Attaching to infisical-backend, infisical-db, infisical-db-migration, infisical-dev-redis
infisical-dev-redis     | 1:C 04 Jan 2025 16:39:30.000 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
infisical-dev-redis     | 1:C 04 Jan 2025 16:39:30.000 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
infisical-dev-redis     | 1:C 04 Jan 2025 16:39:30.000 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=1, just started
infisical-dev-redis     | 1:C 04 Jan 2025 16:39:30.000 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.000 * monotonic clock: POSIX clock_gettime
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.001 * Running mode=standalone, port=6379.
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.001 * Server initialized
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.001 * Loading RDB produced by version 7.4.1
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.001 * RDB age 28 seconds
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.001 * RDB memory usage when created 0.91 Mb
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.002 * Done loading RDB, keys loaded: 28, keys expired: 0.
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.002 * DB loaded from disk: 0.000 seconds
infisical-dev-redis     | 1:M 04 Jan 2025 16:39:30.002 * Ready to accept connections tcp
infisical-db            | 
infisical-db            | PostgreSQL Database directory appears to contain a database; Skipping initialization
infisical-db            | 
infisical-db            | 2025-01-04 16:39:30.037 UTC [1] LOG:  starting PostgreSQL 14.15 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
infisical-db            | 2025-01-04 16:39:30.037 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
infisical-db            | 2025-01-04 16:39:30.037 UTC [1] LOG:  listening on IPv6 address "::", port 5432
infisical-db            | 2025-01-04 16:39:30.042 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
infisical-db            | 2025-01-04 16:39:30.048 UTC [26] LOG:  database system was shut down at 2025-01-04 16:39:02 UTC
infisical-db            | 2025-01-04 16:39:30.054 UTC [1] LOG:  database system is ready to accept connections
infisical-db            | 2025-01-04 16:39:35.038 UTC [40] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:35.042 UTC [41] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:40.087 UTC [49] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:40.091 UTC [50] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:45.135 UTC [58] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:45.139 UTC [59] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:50.184 UTC [67] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:50.188 UTC [68] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:55.232 UTC [76] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:39:55.236 UTC [77] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:00.289 UTC [86] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:00.293 UTC [87] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:05.347 UTC [95] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:05.353 UTC [96] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:10.407 UTC [104] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:10.411 UTC [105] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:15.460 UTC [113] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:15.465 UTC [114] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:20.510 UTC [122] FATAL:  role "infisical" does not exist
infisical-db            | 2025-01-04 16:40:20.515 UTC [123] FATAL:  role "infisical" does not exist
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container infisical-db is unhealthy

```
