### ISSUE TITLE
Failed Infisical Agent on AWS ECS Fargate

### ISSUE THREAD

**Issue by douglasqueirozalmeida** [Infisical/infisical#3040]
### Describe the bug
I'm configuring the infisical agent in my ecs - fargate environment. However, I get this message at the end of the deployment.

`create failed: unable to start container process: error during container init: error creating device nodes: mknod /run/containerd/io.containerd.runtime.v2.task/fargate.task/8db469a99ca74105bfd3cb2001db711a-3906875064/rootfs/dev/null: errno 524`

`image       = "infisical/cli:0.34.1"`

### To Reproduce
This documentation is step by step.

[https://infisical.com/docs/integrations/platforms/ecs-with-agent](https://infisical.com/docs/integrations/platforms/ecs-with-agent)

### Expected behavior
EFS and Fargate on

### Screenshots

<img width="1081" alt="Image" src="https://github.com/user-attachments/assets/4daca58d-4f64-439d-a4c8-6b8c5feb1113" />

<img width="1066" alt="Image" src="https://github.com/user-attachments/assets/fd321e80-4447-40fc-a720-97ffb7f439cb" />

### Platform you are having the issue on: 

aws - ecs

### Additional context
```
{
      name        = "infisical-agent",
      image       = "infisical/cli:0.34.1",
      cpu         = 1024
      memory      = 1024
      networkMode = "awsvpc",
      command     = ["agent"],
      essential   = false,
      logConfiguration = {
        logDriver = "awslogs",
        options = {
          awslogs-group         = "/ecs/agent",
          awslogs-region        = "us-east-1",
          awslogs-stream-prefix = "ecs"
        }
      },
      healthCheck = {
        command     = ["CMD-SHELL", "agent", "--help"],
        interval    = 30,
        timeout     = 5,
        retries     = 3,
        startPeriod = 0
      },
      environment = [
        {
          name  = "INFISICAL_MACHINE_IDENTITY_ID"
          value = "xxxxx"
        },
        {
          name  = "INFISICAL_AGENT_CONFIG_BASE64"
          value = base64encode(file("${path.module}/agent-config.yaml"))
        }
      ],
      mountPoints = [
        {
          containerPath = "/infisical-agent",
          sourceVolume  = "infisical-efs",
          readOnly      = false
        }
      ]
    }
```

**Comment by douglasqueirozalmeida** [comment]
```
infisical:
  address: https://app.infisical.com
  exit-after-auth: true
auth:
  type: aws-iam
sinks:
  - type: file
    config:
      path: /infisical-agent/access-token
templates:
  - template-content: |
      {{- with secret "xxxxxxxx" "homol" "/" }}
      {{- range . }}
      {{ .Key }}={{ .Value }}
      {{- end }}
      {{- end }}
    destination-path: /infisical-agent/secrets

```
