### ISSUE TITLE
Failed Agent Infisical create files in EFS

### ISSUE THREAD

**Issue by douglasqueirozalmeida** [Infisical/infisical#3043]
### Describe the bug
Agent Infisical runs but does not create files with the token and secrets.

### To Reproduce
step by step
[https://infisical.com/docs/integrations/platforms/ecs-with-agent](https://infisical.com/docs/integrations/platforms/ecs-with-agent)

### Expected behavior
Files in EFS

### Screenshots

![Image](https://github.com/user-attachments/assets/2ceec780-ceda-4673-aac8-028b6a1df3b6)
![Image](https://github.com/user-attachments/assets/df528316-d7e8-429f-9ee7-92d04b2ab72e)

### Platform you are having the issue on:

AWS -> ECS FARGATE

### Additional context
```
{
      name        = "infisical-agent",
      image       = "infisical/cli:0.34.1",
      cpu         = 1024
      memory      = 1024
      networkMode = "awsvpc",
      command     = ["agent"],
      essential   = false,
      logConfiguration = {
        logDriver = "awslogs",
        options = {
          awslogs-group         = "/ecs/agent",
          awslogs-region        = "us-east-1",
          awslogs-stream-prefix = "ecs"
        }
      },
      healthCheck = {
        command     = ["CMD-SHELL", "agent", "--help"],
        interval    = 30,
        timeout     = 5,
        retries     = 3,
        startPeriod = 0
      },
      environment = [
        {
          name  = "INFISICAL_MACHINE_IDENTITY_ID"
          value = "xxxxx"
        },
        {
          name  = "INFISICAL_AGENT_CONFIG_BASE64"
          value = base64encode(file("${path.module}/agent-config.yaml"))
        }
      ],
      mountPoints = [
        {
          containerPath = "/infisical-agent",
          sourceVolume  = "infisical-efs",
        }
      ]
    }
```

```
volume {
    name = "infisical-efs"
    efs_volume_configuration {
      file_system_id = "fs-0dc32d6c9e9883bcd"
      root_directory = "/"
    }
  }
```

```
infisical:
  address: https://app.infisical.com
  exit-after-auth: true
auth:
  type: aws-iam
sinks:
  - type: file
    config:
      path: /infisical-agent/access-token
templates:
  - template-content: |
      {{- with secret "xxxxx" "dev" "/" }}
      {{- range . }}
      {{ .Key }}={{ .Value }}
      {{- end }}
      {{- end }}
    destination-path: /infisical-agent/secrets
```
