### ISSUE TITLE
[Helm Secrets Operator] strict decoding error: unknown field "spec.authentication.universalAuth", unknown field "spec.managedKubeSecretReferences"

### ISSUE THREAD

**Issue by ku9nov** [Infisical/infisical#3084]
### Describe the bug
After installing the Secrets Operator via the Helm chart, I can’t apply the InfisicalSecret CRD because of multiple unknown field errors.

### To Reproduce
1. helm repo add infisical-helm-charts 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/' 
2. helm install infisical infisical-helm-charts/secrets-operator
3.   kubectl create secret generic universal-auth-credentials --from-literal=clientId="<your-identity-client-id>" --from-literal=clientSecret="<your-identity-client-secret>"
4. Try to apply InfisicalSecret CRD. Example:
```
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret
  namespace: "default"
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: "https://infisical.self.hosted"
  resyncInterval: 60
  authentication:
      universalAuth:
          credentialsRef:
              secretName: universal-auth-credentials # <-- name of the Kubernetes secret that stores our machine identity credentials
              secretNamespace: "default"
          secretsScope:
            projectSlug: "example-wq-om"
            envSlug: "dev" # Generated based on inventory file
            secretsPath: "/"
  managedKubeSecretReferences:
    - secretName: "infisical-secret" # <-- the name of kubernetes secret that will be created
      secretNamespace: "default"
      template:
        includeAllSecrets: true
```

### Expected behavior
InfisicalSecret CRD should be applied. 

### Expected behavior
Actual result:
`strict decoding error: unknown field "spec.authentication.universalAuth", unknown field "spec.managedKubeSecretReferences"`

### Platform you are having the issue on:
OSS k8s, self hosted infisical instance on additional server.
### Additional context
Self hosted Infisical version: v0.106.0-postgres

Helm chart version: 0.8.9

Used docs pages:

https://infisical.com/docs/integrations/platforms/kubernetes/overview

https://infisical.com/docs/integrations/platforms/kubernetes/infisical-secret-crd#authentication-universalauth
