### ISSUE TITLE
Permit to enable the metrics port via helm chart

### ISSUE THREAD

**Issue by jorgelon** [Infisical/infisical#3382]
### Feature description
I am trying to enable the prometheus metrics using  the helm chart. For this I include  the following env variables in the infisical-secrets secret

```
OTEL_TELEMETRY_COLLECTION_ENABLED: "true"
OTEL_EXPORT_TYPE: "prometheus"
```

I have also created a podmonitor using prometheus operator matching the infisical pod but i have to enable the metrics port in the pod (9464) and this cannot be achieved using the helm chart.

It can be useful to enable the metrics port in the infisical deployment.

### Why would it be useful?
This permits to make prometheus operator podmonitor work with self hosted infisical in order to get metrics 

### Additional context
I am using infisical v0.120.0-postgres image and helm chart 1.5.0

**Comment by lytt925** [comment]
Hi @maidul98, I’d love to help with this issue in the Helm chart template if it’s still unassigned. It looks like we just need to add containerPort: 9464 and a matching service port in the helm template. Is that correct?

**Comment by satvik2131** [comment]
@jorgelon , is this issue still there ?

**Comment by jorgelon** [comment]
Finally i have achieved that with the following podmonitor, thank you

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: infisical
spec:
  podMetricsEndpoints:
    - path: /metrics
      portNumber: 9464
  selector:
    matchLabels:
      app: infisical
      component: infisical
  ...
```
