### ISSUE TITLE
Kubernetes CRD can't pull secrets when the key has a hyphen

### ISSUE THREAD

**Issue by chakraborty29** [Infisical/infisical#3496]
### Describe the bug
Infisical K8s CRDs is unable to pull secrets when the key has a hyphen.

### To Reproduce
1. Create a secret in Infisical webapp with a key of `redis-password` & `password`
2. Create a `InfisicalSecret` CRD referencing `redis-password`
```
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-authentik-redis-credentials-secret
  namespace: authentik
spec:
  hostAPI: ""
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
      secretsScope:
        projectSlug: ""
        envSlug: prod
        secretsPath: ""
        recursive: true
  managedKubeSecretReferences:
    - secretName: authentik-redis-admin-credentials-secret
      secretNamespace: authentik
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: false
        data:
          redis-password: "{{ .redis-password.Value }}"

```
3. Apply CRD, and the secret resource `authentik-redis-admin-credentials-secret` in the namespace `authentik` is not created.
4. Update the `InfisicalSecret` CRD to reference `password`
```
...
      template:
        includeAllSecrets: false
        data:
          redis-password: "{{ .password.Value }}"
```
5. You will now see the secret resource `authentik-redis-admin-credentials-secret` in the `authentik` namespace

### Expected behavior
I would expect, no matter the name of the key of the secret, I would be able to pull the secret. Why does a hyphen matter? Is this something with the Kubernetes CRD that is causing the issue or is it a bug within the Infisical code base? 

### Screenshots

![Image](https://github.com/user-attachments/assets/9645eb13-4205-4d9e-b645-5371b62625b6)

### Platform you are having the issue on:
Kubernetes
