### ISSUE TITLE
Type error when adding 1Password Secrets Sync

### ISSUE THREAD

**Issue by undaunt** [Infisical/infisical#3764]
### Describe the bug
When attempting to add a 1Password Secrets Sync on a self-hosted Infisical installation I am getting a TypeError. `s.find is not a function.`

![Image](https://github.com/user-attachments/assets/dc9058c9-9197-4f69-a665-6c8883bd462b)

```
index-DMhR68rG.js:9 TypeError: s.find is not a function
    at Object.render (GitHubSyncSelectedRepositoriesTooltipContent-CwGkNziD.js:1:15630)
    at Controller (index-DMhR68rG.js:659:282175)
    at Nh (index-DMhR68rG.js:7:18943)
    at cj (index-DMhR68rG.js:9:3539)
    at Vk (index-DMhR68rG.js:9:49661)
    at Uk (index-DMhR68rG.js:9:43997)
    at Tk (index-DMhR68rG.js:9:43918)
    at Ik (index-DMhR68rG.js:9:43758)
    at Nk (index-DMhR68rG.js:9:39704)
    at Ek (index-DMhR68rG.js:9:40600)
```

### To Reproduce
1. Go to a project within secrets management.
2. Open the integrations tab.
3. Add sync and select 1Password.
4. Adter entering an environment and path, hit next.
5. As soon as the connection is chosen, before the vault is able to be chosen, the GUI crashes to aforementioned error.

https://github.com/user-attachments/assets/75ddc368-853c-4810-9d3b-446a4f72ba57

### Expected behavior
I expect to be able to proceed through the steps and configure 1Password secrets sync as described here: https://infisical.com/docs/integrations/secret-syncs/1password

### Screenshots
See above.

### Platform you are having the issue on:
Docker compose, amd64.

**Comment by sidwebworks** [comment]
@undaunt Hey, looks like you're getting a malformed response from the [Connect API](https://developer.1password.com/docs/connect/api-reference) - can you please confirm if you're able to connect to it directly? 

Try this curl

```js
curl \
    -H "Accept: application/json" \
    -H "Authorization: Bearer <API_TOKEN>" \
    http://<CONNECT_API_HOST>/v1/vaults
```

Also incase you have changed the port mapping for the `connect-api` container, remember to override the `OP_HTTP_PORT` in the environment section of the docker compose file.

Here is an example file 

```yaml
version: "3.4"

services:
  op-connect-api:
    image: 1password/connect-api:latest
    environment:
      - OP_HTTP_PORT=8090
    ports:
      - "8090:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  op-connect-sync:
    image: 1password/connect-sync:latest
    environment:
      - OP_HTTP_PORT=8091
    ports:
      - "8091:8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"

volumes:
  data:

```
