### ISSUE TITLE
Helm Deployment: Pods crash on POST

### ISSUE THREAD

**Issue by Ergamon** [Infisical/infisical#3811]
I followed the self hosting instructions on your page. The clusters I tried installation in are all on premise with traefik as ingress installed.

So my values.yaml looks like this:
```
infisical:
  image:
    tag: "v0.132.4-postgres"

ingress:
  hostName: "example.com"
  ingressClassName: ~
  nginx:
    enabled: false
```

basically I use the latest image with a defined host and the default ingress.
(No annotations/labels necessary, the default is configured to use TLS)

I also created a secret like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  AUTH_SECRET: xxx
  ENCRYPTION_KEY: xxx
  SITE_URL: https://example.com
```
I deployed it with the helm chart and the values.

I can open the web page but if I try to trigger some actions the pod crashes. Basically GET works, POST not.

E.g. wenn I try to log on with the mail/password I created I see the following in the log:
```
{"level":30,"time":1750196398673,"pid":1,"hostname":"infisical-infisical-standalone-infisical-588456c4c-r56p2","reqId":"req-4slZris8YDd5ht","severity":"INFO","req":{"method":"POST","url":"/api/v3/auth/login2","hostname":"example.com","remoteAddress":"172.21.83.134","remotePort":55846},"msg":"incoming request"}
```
This is the last line in the log, the pod now crashes and starts fresh.

What am I doing wrong? Thanks for any help
