### ISSUE TITLE
`Failed to create workspace` - error on new self-hosted instance

### ISSUE THREAD

**Issue by arpadgabor** [Infisical/infisical#473]
### Describe the bug
Trying to deploy a new instance using docker compose and after creating the account and confirming my email, a 400 error is thrown in the network, not creating the workspace. If I refresh, I'm able to login however I cannot create any new project as those requests also throw a 400 error.

### To Reproduce

I'm using this yaml (adapted to be used with portainer and an external reverse proxy). Requests are all proxied to the API so there is no issue on the proxy side. Also no logs show up in the container.

```yml
services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    depends_on:
      - mongo
    image: infisical/backend
    ports:
      - 40000:4000
    environment:
      - NODE_ENV=production
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SIGNUP_SECRET=${JWT_SIGNUP_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_AUTH_SECRET=${JWT_AUTH_SECRET}
      - JWT_SERVICE_SECRET=${JWT_SERVICE_SECRET}
      - MONGO_URL=${MONGO_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      #- INVITE_ONLY_SIGNUP=true

  frontend:
    container_name: infisical-frontend
    restart: unless-stopped
    ports:
      - 30000:3000
    depends_on:
      - backend
    image: infisical/frontend
    environment:
      - SITE_URL=${SITE_URL}

  mongo:
    container_name: infisical-mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

```

### Expected behavior

Should not throw 400 and allow me to create projects.

### Screenshots

![image](https://user-images.githubusercontent.com/9270494/228978133-147f712c-779d-4cc5-8d7e-cae138ad8230.png)

Request payload:

```json
{"workspaceName":"Example Project","organizationId":"64260bf0e3afca83b72ae0dd"}
```

### Platform you are having the issue on:

Docker inside CentOS.

### Additional context

n/a
