### ISSUE TITLE
Fetch secrets failed: token allows [x] environment access, not [y] during CI build.

### ISSUE THREAD

**Issue by Oigen43** [Infisical/infisical#516]
### Describe the bug
Hello, after merging this [commit](https://github.com/Infisical/infisical/commit/5922921896ab8185bde9c362e72f309238c8af19
), release v0.4.1 we have encountered the next bug. Appreciate any help :)
```
Fetch secrets failed: token allows [dev] environment access, not [staging]. Service tokens are environment-specific; no need for --env flag.
```

We build Docker images inside GitHub Actions and use service tokens to retrieve secrets from Infisical Cloud. Also, we have 2 environments with `dev` and `staging` slugs. We have only one configured service token at Infisical Cloud, which is tied to`staging` environment. I highlighted the essential steps of our build setup.

**Workflow step**
```
- name: Build, tag, and push image
  id: build-image
  env:
    INFISICAL_TOKEN: ${{ secrets.INFISICAL_FRONTEND_TOKEN_STAGING }}
  run: |
    DOCKER_BUILDKIT=1 docker build \
    --build-arg INFISICAL_TOKEN=$INFISICAL_TOKEN \
```

**Dockerfile commands**
```
ARG INFISICAL_TOKEN
ENV INFISICAL_TOKEN=$INFISICAL_TOKEN

# Install Infisical CLI
RUN apk add --no-cache curl bash sudo && \
  curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash && \
  apk update && sudo apk add infisical

RUN pnpm turbo build:$NEXT_PUBLIC_APP_ENV --filter=portal-web
```

**package.json**
```
"build:staging": "infisical run -- next build",
```

### Platform you are having the issue on:
GitHub Actions 
`runs-on: ubuntu-20.04`
