### ISSUE TITLE
Server Logs Out on Refresh

### ISSUE THREAD

**Issue by rahb3rt** [Infisical/infisical#559]
### Describe the bug
When logged in on-prem/self-hosted and you refresh the page or let the session become stale for to long navigating to another page or just refreshing the page will log you out. 

### To Reproduce
1. Log in 
2. Wait for a bit or just hit refresh (safari) and the page logs you out. 

### Expected behavior
I should be able to refresh the page and stay logged in. Or navigate away and stay logged in.

### Platform you are having the issue on:
EKS
Browser - Safari/Chrome

**Comment by maidul98** [comment]
investigating

**Comment by maidul98** [comment]
Config issue, fixed with 

```
frontend:
  name: frontend
  image:
    tag: "v0.1.1"
    pullPolicy: Always

backend:
  image:
    tag: "v0.1.1"
    pullPolicy: Always

backendEnvironmentVariables:
  HTTPS_ENABLED: "false"
```
