### ISSUE TITLE
First signup fails on a self-hosted setup

### ISSUE THREAD

**Issue by shark0der** [Infisical/infisical#566]
### Describe the bug
When signing up with the first user, after typing the code that is sent via email and typing the account details (name and password) form submission fails probably due to inexistent organization.

### To Reproduce

1. Go to /signup and type in the email address
2. Get the code sent via email and type it in
3. Fill in first/last name and a password.
4. Press enter.

The frontend sends a request to `/api/v2/signup/complete-account/signup` (`200 OK`).
The frontend then sends a request to `/api/v1/organization` which fails with `500` error and the http response body is `{}`.

Same request is observed when trying to login afterwards.

I have `VERBOSE_ERROR_OUTPUT=true` but logs only show this:
```
infisical-backend   | 2023-05-08T16:37:23.757Z [IFSC:backend-main] error: The server encountered an error while processing the request
```

### Expected behavior
Finishing the sign-up process should work.

### Screenshots
Not required.

### Platform you are having the issue on:
```
Ubuntu: 22.04
Docker: 23.0.6-1~ubuntu.22.04~jammy
Docker compose plugin: 2.17.3-1~ubuntu.22.04~jammy

infisical/frontend      latest    eed68a0eb9d8
infisical/backend       latest    99e2e523e1f3
```

**Comment by maidul98** [comment]
@shark0der taking a look at this

**Comment by shark0der** [comment]
Seems like the organization is created successfully in mongo (my initial assumption that it didn't exist was wrong):

```
test> db.organizations.find()
[
  {
    _id: ObjectId("64592331f40653e655c562c1"),
    name: "Anatol's organization",
    createdAt: ISODate("2023-05-08T16:28:33.809Z"),
    updatedAt: ISODate("2023-05-08T16:28:33.809Z"),
    __v: 0
  }
]
```

**Comment by dangtony98** [comment]
Typically, there might be issues if not all required environment variables are set correctly.

**Comment by shark0der** [comment]
Hello! I was able to debug and fix the issue.

I've installed sentry to be able to debug this. Here's the error that I'm getting:

```
[Stack Trace](https://sentry.nexusmutual.io/organizations/nexusmutual/issues/2/?query=&referrer=issue-stream&statsPeriod=14d&stream_index=0#exception)

Newest

Error: The server encountered an error while processing the request
  File "/app/node_modules/jsonwebtoken/verify.js", line 190, col 21, in <anonymous>
    return done(new TokenExpiredError('jwt expired', new Date(payload.exp * 1000)));
  File "/app/node_modules/jsonwebtoken/verify.js", line 97, col 14, in getSecret
    return secretCallback(null, secretOrPublicKey);
  File "/app/node_modules/jsonwebtoken/verify.js", line 101, col 10, in Object.module.exports [as verify]
    return getSecret(header, function(err, secretOrPublicKey) {
  File "/app/build/helpers/auth.js", line 81, col 50, in <anonymous>
    const decodedToken = (jsonwebtoken_1.default.verify(authTokenValue, yield (0, config_1.getJwtAuthSecret)()));
  File "<anonymous>", in Generator.next
  File "/app/build/helpers/auth.js", line 5, col 58, in fulfilled
    function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
  File "node:internal/process/task_queues", line 96, col 5, in processTicksAndRejections
```

This is happening when processing the request to `/api/v1/organization`  which errors out with http 500.

Inspecting the JWT that is sent via the `Authentication` header I've noticed that `iat` and `exp` fields are equal:
![image](https://github.com/Infisical/infisical/assets/528959/d31b36de-a7ac-4355-8100-4d1cfaa4c880)

Here are the JWT config values:
```
# JWT lifetime
# Optional lifetimes for JWT tokens expressed in seconds or a string 
# describing a time span (e.g. 60, "2 days", "10h", "7d")
JWT_AUTH_LIFETIME=60
JWT_REFRESH_LIFETIME=7d
JWT_SIGNUP_LIFETIME=7d
```

After changing the `JWT_AUTH_LIFETIME` to `6h` the issue went away. In retrospective the issue is kind of obvious and setting the value to `60` was a mistake (I was tired and I was mislead by the example). Filling in some sensible defaults might be a good idea. Even thought it was a mistake - I still don't understand why a 60 seconds session would not be a valid value and why does that lead to `iat = exp`?.

You can close the issue if there isn't anything actionable on your side.

Thank you!

**Comment by kxitiz** [comment]
Cannot signup after hosting using docker compose and setting all smtp credentials. Api call retruns error.
![2023-05-12_11-17](https://github.com/Infisical/infisical/assets/42801539/e149b7b0-2832-4db3-96b5-1e081529235e)

**Comment by maidul98** [comment]
@kxitiz Can you remove all smtp environment variables and try again? This is to figure out if the issue is with SMTP credentials or something else

**Comment by stefaanMLB** [comment]
Same problem here, different error message `[IFSC:backend-main] error: The server encountered an error while processing the request` when clicking the 'signup' button.

We're using this docker-compose file 
```yaml
version: "3.3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: <removed>
      MONGO_INITDB_ROOT_PASSWORD: <removed>

  secrets_mgmt:
    image: infisical/infisical:latest
    container_name: secrets_mgmt
    restart: unless-stopped
    ports:
      - "3300:80"
    depends_on:
      - mongo
    environment:
      JWT_SIGNUP_SECRET: <removed>
      JWT_REFRESH_SECRET: <removed>
      JWT_AUTH_SECRET: <removed>
      JWT_MFA_SECRET: <removed>
      JWT_SERVICE_SECRET: <removed>
      SMTP_HOST: <removed>
      SMTP_PORT: 25
      SMTP_USERNAME: <removed>
      SMTP_PASSWORD: <removed>
      SMTP_SECURE: <removed>
      SMTP_FROM_ADDRESS: <removed>
      SMTP_FROM_NAME: IT
      MONGO_URL: mongodb://xxx:yyy@mongo:27017/
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
```
