### ISSUE TITLE
[HELM-CHART] INVITE_ONLY_SIGNUP env variable seem to have no effect on signUp

### ISSUE THREAD

**Issue by AurelienConte** [Infisical/infisical#577]
### Describe the bug

I have installed the helm chart on a kubernetes and specified INVITE_ONLY_SIGNUP to true but i'm always able to signup without having being invited to do it. (SMTP config is also disabled, so i should not be able to signup at all)

### To Reproduce

Apply this values.yaml for your infiscal deployment:

```yaml
ingress:
  nginx:
    enabled: false #I'm using Traefik -> k3s kube

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: infisical/frontend
    tag: "v0.1.3"
    pullPolicy: Always

backend:
  replicaCount: 1
  image:
    repository: infisical/backend
    tag: "v0.1.3"
    pullPolicy: Always

backendEnvironmentVariables:
  HTTPS_ENABLED: true
  MONGO_URL: "mongodb://infiscal:infiscal@mongodb-service.infiscal.svc.cluster.local:27017"
  INVITE_ONLY_SIGNUP: true
  SITE_URL: "https://mysite.fr"

frontendEnvironmentVariables:
  SITE_URL: "https://mysite.fr"

# I'm using ARM arch so i can not use the bitnami mongo, i have an another deployment for this
mongodb:
  enabled: false
  persistence:
    enabled: false


ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  hostName: mysite.fr
  frontend:
    path: /
    pathType: Prefix
  backend:
    path: /api
    pathType: Prefix
  tls:
    - secretName: infiscal-tls
      hosts:
        - mysite.fr
```

Apply the values.yaml with helm : 

```bash
 helm install -f values.yaml -n infiscal infiscal infisical-helm-charts/infisical
```

### Expected behavior

With this configuration i should not be able to signup. (via the frontend or via the backend)

### Platform you are having the issue on:

Applying this configuration in a k3s cluster on arm arch. Using helm to deploy and traefik ingress to expose the service.

### Screenshoots

Documentation: 

![image](https://github.com/Infisical/infisical/assets/39769262/41403b08-a7d8-4b89-8139-e57a39d0bd79)

Pod env : 

![image](https://github.com/Infisical/infisical/assets/39769262/f2ae4c02-1565-45e6-b52d-9a85584f245e)

Ability to sign up : 

![image](https://github.com/Infisical/infisical/assets/39769262/71aa1fed-5614-43ee-8262-13037b7e5c59)

(I have completed the signup process two times to confirm that is always working)
