### ISSUE TITLE
Cannot assign project permissions to service account

### ISSUE THREAD

**Issue by skriems** [Infisical/infisical#615]
First things first! Thanks for this project and all your effort !! :)

### Describe the bug

Cannot assign project permissions to service account.

### To Reproduce

1. Go to current organisation
2. Create a service account
3. Click on the pencil and try to add read permissions to the service account.
4. Paste the private key from the previous screen
5. Click on "save" -> loading spinner keeps spinning all day long

### Expected behavior

I'm able to add permissions to the service account.

### Platform you are having the issue on:

We've deployed Infisical in our Kubernetes cluster with the following values

```
    backend:
      replicaCount: 2
      image:
        repository: infisical/backend
        tag: "v0.1.3"
        pullPolicy: Always

    backendEnvironmentVariables:
      SITE_URL: https://<redacted>
      HTTPS_ENABLED: false
      INVITE_ONLY_SIGNUP: true
      SMTP_HOST: <redacted>
      SMTP_FROM_ADDRESS: <redacted>
      SMTP_USERNAME: <redacted>
      SMTP_PASSWORD: <redacted>

    frontend:
      name: frontend
      replicaCount: 2
      image:
        repository: infisical/frontend
        tag: "v0.1.3"
        pullPolicy: Always

    frontendEnvironmentVariables:
      SITE_URL: https://<redacted>

    mongodb:
      enabled: true
      fullnameOverride: infisical-production-mongodb
      persistence:
        enabled: true
        existingClaim: pvc-infisical-production
        accessModes: ["ReadWriteMany"]

    ingress:
      nginx:
        enabled: false
```

We have a dedicated ingress configured so that our ssl certificates do not get removed accidentally.  It is configured like the original one to route `/api` traffic to the backend on port 4000 and `/` to the frontend port 3000.

### Additional context

I can pull secrets with the CLI locally but I'm currently having troubles with service _tokens_ and service _accounts_.

With the former the secrets-operator yells about not finding any authentication information in the InfisicalSecret manifest (although it's there) and the latter I cannot connect to my projects.
