### ISSUE TITLE
Are the helm docs correct?

### ISSUE THREAD

**Issue by JamesArthurHolland** [Infisical/infisical#674]
### Describe the bug
Current docs are this:
```
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret-sample
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: https://app.infisical.com/api
  authentication:
    serviceToken: 
      serviceTokenSecretReference: # <-- The secret's namespaced name that holds the project token for authentication in step 1
        secretName: service-token
        secretNamespace: option
  managedSecretReference: 
    secretName: managed-secret # <-- the name of kubernetes secret that will be created
    secretNamespace: default # <-- in what namespace it will be created in
```

I don't think it's possible to use a secret from another namespace, so it's necessary that the service-token has to be created in the same namespace as the InfisicalSecret.

In which case, it's misleading to have multiple references to "secretNamespace" as this makes it seem like the token can be added once and used anywhere.

`secretNamespace: option`

So in step one, the namespace isn't mentioned:

`kubectl create secret generic service-token --from-literal=infisicalToken=<your-service-token-here> `

There is no namespace used, so I'm pretty sure the following won't work either:

`kubectl apply -f infisical-secrets-config.yaml`

if it is from `default` ns, it is trying to be attempting to use a secret from `option` namespace, which is impossible.

I think the docs were written by someone that was using `kubens` in the namespace `option`, which has hidden a lot of the context of what is happening.
