### ISSUE TITLE
Specify secret path in InfisicalSecrets CRD yaml file

### ISSUE THREAD

**Issue by jeannot-ranaivosoa** [Infisical/infisical#826]
### Describe the bug

Hi all, 

I have just deployed infisical and its operator on my kubernetes cluster. 
I am using the last version of infisical  (and the operator as well). 
In infisical, i have created a folder name my_app and added some secrets inside it.

My issues comes when i try to specify a specific secret path in my infisicalsecrets yaml file 

```yaml infisical-secrets-config.yaml
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret-sample
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: https://my-host.com/api
  resyncInterval:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: option
      secretsScope:
        envSlug: dev
        secretsPath: "/my_app"
  managedSecretReference:
    secretName: managed-secret # <-- the name of kubernetes secret that will be created
    secretNamespace: default # <-- where the kubernetes secret should be created
```

Looking at my operator logs , it shows : 
```Unsuccessful response. Please make sure your secret path, workspace and environment name are all correct [response={}]]]. Will requeue after [requeueTime=1m0s]```

### To Reproduce

1. Deploy last version of infisical and corresponding operator. 
2. Create a folder named my_app  in infisical and add some secrets inside it. 
3. Apply the infisicalsecrets crd yaml file below 
```yaml infisical-secrets-config.yaml
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret-sample
spec:
  # The host that should be used to pull secrets from. If left empty, the value specified in Global configuration will be used
  hostAPI: https://my-host.com/api
  resyncInterval:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: option
      secretsScope:
        envSlug: dev
        secretsPath: "/my_app"
  managedSecretReference:
    secretName: managed-secret # <-- the name of kubernetes secret that will be created
    secretNamespace: default # <-- where the kubernetes secret should be created
```

### Expected behavior

Infisical operator create a k8s secret  in accordance with  what was specified inside InfisicalSecret crd yaml file. Looks for the secrets inside my_app folder and create k8s secrets with values inside my_app fodler accordingly.

Kind regards
